MWPW-134057 | Replace image links in place
adobecom/milo pull request #1018
Opened 2023-07-27 12:16 UTC by aishwaryamathuria

* If there is an image in Milo with alt text having '|' it is replaced with an a tag and the image element is added inside the a tag. The a tag is then added to the end of the parent element of image. This removes the image from its initial position in the parent element and adds it to the end of the container.
* The change in the PR replaces the image in place. The a tag is added before the image and then the image is shifted inside the 'a' tag keeping the image position same.

Resolves: [MWPW-134057](https://jira.corp.adobe.com/browse/MWPW-134057)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/mathuria/mwpw-134057?martech=off
- After: https://miloimglnk--milo--aishwaryamathuria.hlx.page/drafts/mathuria/mwpw-134057?martech=off

2023-07-27 16:09 UTC, aishwaryamathuria commented on libs/utils/utils.js
> +      const aTag = createTag('a', { href: url, class: 'image-link' });
@mokimo Thanks for sharing the feedback. I have pushed a unit test to verify that the the image link is replaced in place.

2023-07-27 17:04 UTC, ryanmparrish approved these changes

2023-07-27 17:06 UTC, Ruchika4 commented
Hi @aishwaryamathuria , could please address the lint issues in the PR

2023-07-27 17:14 UTC, ryanmparrish requested changes
Looks like one too many `../` in the utils path -> test.js file. 

```
import { decorateImageLinks } from '../../libs/utils/utils.js';
```

2023-07-27 17:43 UTC, chrischrischris approved these changes

2023-07-27 18:40 UTC, ryanmparrish approved these changes

2023-07-27 22:51 UTC, Ruchika4 approved these changes

2023-07-28 08:26 UTC, mokimo approved these changes

2023-07-28 18:12 UTC, sukamat approved these changes

2023-07-31 09:05 UTC, overmyheadandbody approved these changes

2023-07-31 14:35 UTC, aishwaryamathuria commented
@chrischrischris Could you please confirm if we can merge this PR?

2023-08-07 05:53 UTC, merged