MWPW-129922 - Consonant Actions Blocks
adobecom/milo pull request #1118
Opened 2023-08-16 21:50 UTC by Sartxi

New consonant blocks for building a set of clickable images with adjoining buttons, icons, and text.
1. Action Item Block: block for rendering an image with wrapped link with a few variants for floating buttons and icons.
2. Action Scroller Block: block for putting action items in a horizontal scrolling container with variant for navigation.

Resolves: [MWPW-129922](https://jira.corp.adobe.com/browse/MWPW-129922)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/sarchibeque/action-blocks?martech=off
- After: https://sarchibeque-actions-blocks--milo--adobecom.hlx.page/drafts/sarchibeque/action-blocks?martech=off

2023-08-17 17:52 UTC, elan-tbx requested changes

2023-08-17 18:02 UTC, Sartxi commented on libs/blocks/action-scroller/action-scroller.css
> +  border-color: var(--action-scroller-button-border-color);
Good catch, fixed

2023-08-17 18:02 UTC, Sartxi commented on libs/blocks/action-scroller/action-scroller.js
> +const NEXTBUTTON = `<button class="nav-button next-button"><img class="next-icon" alt="Next icon" src="${base}/blocks/carousel/img/arrow.svg" height="10" width="16"></button>`;
yeah good idea

2023-08-17 18:03 UTC, elan-tbx approved these changes

2023-08-18 17:21 UTC, ryanmparrish approved these changes

2023-08-21 22:02 UTC, rgclayton approved these changes
Thanks for the updates Sean!

2023-08-22 19:19 UTC, merged