Add chart init tests MWPW-115222
adobecom/milo pull request #128
Opened 2022-08-22 22:31 UTC by meganthecoder

* Add tests for chart init

Resolves: [MWPW-115222](https://jira.corp.adobe.com/browse/MWPW-115222)

**Test URLs:**
- Before: https://data-viz--milo--adobecom.hlx.page/drafts/data-viz/holiday-report-dev
- After: https://chart-test1--milo--adobecom.hlx.page/drafts/data-viz/holiday-report-dev

2022-08-22 23:08 UTC, Brandon32 commented on libs/blocks/chart/chart.js
> +      const result = await Promise.all([fetchData(dataLink), import('./list.js')]);
We don't want to use await here, we will have render issues again.

2022-08-22 23:09 UTC, Brandon32 commented on libs/blocks/chart/chart.js
> +      const values = await Promise.all([fetchData(dataLink), loadScript('/libs/deps/echarts.common.min.js')]);
Same, don't want to wait for json and echarts to load.

2022-08-22 23:14 UTC, Brandon32 commented
Looks like there is some overlap between our two tickets. 
You could use waitForElement in tests instead of adding await to the promises.

2022-08-22 23:14 UTC, Brandon32 requested changes
Looks like there is some overlap between our two tickets.
You should use waitForElement in tests instead of adding await to the promises.

2022-08-22 23:48 UTC, meganthecoder commented
@Brandon32 I forgot about that issue. Thanks for the reminder. I've updated based on your comments and I added a code comment as a future reminder

2022-08-23 00:04 UTC, Brandon32 commented on test/blocks/chart/chart.test.js
> +    expect(init(el)).to.be.undefined;
`init()` doesn't return anything so this will always be undefined.

2022-08-23 00:10 UTC, Brandon32 commented on test/blocks/chart/chart.test.js
> +    const parsedData = JSON.parse(data);
Is `JSON.parse(data)` needed? `fetchData` uses `resp.json()` so I would think it's being parsed after the fetch but I'm not familiar with stubs.

2022-08-23 00:11 UTC, Brandon32 approved these changes

2022-08-23 12:00 UTC, auniverseaway approved these changes

2022-08-23 17:51 UTC, merged