Potential solution to support multiple locales
adobecom/milo pull request #1323
Opened 2023-09-21 02:37 UTC by sanrai

* Add your
* Specific
* Features or fixes

Resolves: [MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-NUMBER)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/?martech=off
- After: https://<branch>--milo--adobecom.hlx.page/?martech=off

2023-09-21 12:25 UTC, overmyheadandbody reviewed
Same PR pollution comment, PRs should be opened only after they're ready for others to review.

2023-09-22 14:37 UTC, cmiqueo approved these changes

2023-09-22 14:45 UTC, chrischrischris commented on libs/blocks/caas/utils.js
> +const LOCALES = {
Can we combine this and the LOCALES object in send-utils?  I don't think we should have two copies within the caas files.

2023-09-22 14:45 UTC, chrischrischris commented on libs/blocks/caas/utils.js
> +const LOCALES = {
I know this was originally copied from the milo locales object, but I don't think we need the `ietf` subobject:
```
const LOCALES = {
  ar: 'es-AR',
  br: 'pt-BR',
  ...
};
```

2023-09-22 14:45 UTC, chrischrischris commented on libs/blocks/caas/utils.js
> +const LOCALES = {
nit: Please alpha sort within each region

2023-09-22 14:45 UTC, chrischrischris requested changes
Adding request changes to prevent from merging until the LOCALES obj location can be figured out.

2023-09-23 01:02 UTC, sanrai commented
As discussed, moved code to one PR: https://github.com/adobecom/milo/pull/1324

2023-09-23 01:02 UTC, closed without merging