Implemented disabling scroll when modal with curtain is opened
adobecom/milo pull request #1466
Opened 2023-10-30 11:49 UTC by saragajic11

This PR has been opened because previous 2 had outdated and broken main origin branch. I am opening this PR after cloning this project from the start, with fresh and up-to-date main branch.

This PR should resolve the issue of scrollable background when modal dialog (which is authored to have a 'curtain') is opened. In other cases (with 'curtain-off') background should be scrollable per requirements.

Resolves: [MWPW-136767](https://jira.corp.adobe.com/browse/MWPW-136767)

Test URLs:

Before: https://main--milo--adobecom.hlx.page/drafts/rclayton/video-examples?martech=off
After: https://mwpw-136767-modal-background-scroll--milo--saragajic11.hlx.page/drafts/rclayton/video-examples?martech=off

Commerce dialog (it should work the same as before this PR):

Before: https://main--milo--adobecom.hlx.page/drafts/ruchika/discover1?martech=off
After: https://mwpw-136767-modal-background-scroll--milo--saragajic11.hlx.page/drafts/ruchika/discover1?martech=off

Example of page which had (in previous PR) _content_ issues:
https://main--cc--adobecom.hlx.page/creativecloud/animation/discover?milolibs=mwpw-136767-modal-background-scroll--milo--saragajic11

2023-10-30 15:51 UTC, fullcolorcoder approved these changes

2023-10-30 16:20 UTC, narcis-radu commented
Hey @saragajic11, can you please update the description to reference and close the previous PRs?
* https://github.com/adobecom/milo/pull/1457
* https://github.com/adobecom/milo/pull/1419

2023-10-31 09:36 UTC, narcis-radu requested changes

2023-10-31 09:48 UTC, saragajic11 commented on libs/blocks/modal/modal.js
> +    if (!document.querySelectorAll('.modal-curtain').length) {
good catch, updated: https://github.com/adobecom/milo/pull/1466/commits/f99ec9e00a1cfec161fa4baef1380562f81ecdc3 thanks! @narcis-radu

2023-10-31 10:08 UTC, Snehayt commented
Verified the flow in all the browsers(firefox,brave,chrome and edge) in desktop,mac and devices.Works as expected.

![image](https://github.com/adobecom/milo/assets/144407787/56d7db3f-12fd-4791-b44d-8306c1e68681)
![image](https://github.com/adobecom/milo/assets/144407787/b6a3681d-a7e0-4bba-a21f-0e4231d188fb)
![image](https://github.com/adobecom/milo/assets/144407787/4377c7f3-9792-4898-9444-90cb1118ac87)

2023-10-31 12:11 UTC, narcis-radu approved these changes

2023-10-31 12:12 UTC, narcis-radu commented
Looks good 👍 ! You might want to add some unit tests.

2023-11-01 16:30 UTC, Ruchika4 approved these changes

2023-11-06 16:16 UTC, merged