MWPW-105618 - Consonant Icon block
adobecom/milo pull request #148
Opened 2022-08-29 21:57 UTC by Sartxi

* Added support for Consonant 'Icon' blocks

Resolves: [MWPW-105618](https://jira.corp.adobe.com/browse/MWPW-105618)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/sarchibeque/icon-block
- After: https://consonant-icon-block--milo--adobecom.hlx.page/drafts/sarchibeque/icon-block

2022-09-02 03:05 UTC, chrischrischris approved these changes
✅  just two nits

2022-09-02 03:05 UTC, chrischrischris commented on libs/blocks/icon-block/icon-block.js
> +  if (row) {
nit: early return
```suggestion
  if (!row) return;
```

2022-09-02 14:33 UTC, Sartxi commented on libs/blocks/icon-block/icon-block.css
> +/* Vertical */
Thanks, okay I removed the comment

2022-09-02 16:15 UTC, auniverseaway requested changes
I think all the two-up, three-up, four-up and related code needs to be kicked out. This should be handled in section-metadata now.

You all built these when we didn't really have a concept of sections. Now that we do, we can put those styles in there.

```css
.section-metadata.two-up {
  display: grid;
  grid-template-columns: 1fr 1fr;
}
```
...or something like that.

2022-09-06 19:10 UTC, amauch-adobe commented
@Sartxi , were you able to make the changes requested by Chris Millar as mentioned in his comment above?  I'm more than willing to look over this PR and do QA, but I just wanted to make sure I'm looking/testing what really will go out.

2022-09-07 01:20 UTC, amauch-adobe commented
@Sartxi , just notify @auniverseaway when you are ready for him to relook over his requested changes.

2022-09-07 15:28 UTC, Sartxi commented
Hello @auniverseaway I have made updates so that each icon block is now in a segment and uses the style row to set the number of grid columns. @ryanmparrish and I thought it would be good to go with a grid class to apply the proper styles to the segment blocks grid container. Let me know your thoughts. Thanks!

2022-09-07 19:51 UTC, amauch-adobe requested changes
@Sartxi , it looks like there is a responsive design issue with viewing the 2-up/3-up/4-up on mobile.  If you look at the three screenshots below, the 2-up text will get jumbled between the two icon groups when viewed on mobile, 3-up gets cut off slightly on the right side edge of the display, and 4-up only shows 3 of the icon groups instead of the 4th.

![Screen Shot 2022-09-07 at 1 43 40 PM](https://user-images.githubusercontent.com/56042473/188964688-c764fea2-4e71-4d6b-b6cc-8b6cb95ba031.png)
![Screen Shot 2022-09-07 at 1 43 31 PM](https://user-images.githubusercontent.com/56042473/188964693-85336f88-9864-4270-823c-3dd6e2ee369d.png)
![Screen Shot 2022-09-07 at 1 42 44 PM](https://user-images.githubusercontent.com/56042473/188964695-f0a3b718-13ce-4cbe-87d7-835c0f6de33d.png)

2022-09-07 20:09 UTC, Sartxi commented
@amauch-adobe great catch! I have pushed a patch to address the layouts in other viewport sizes. Thank you for noticing this.

2022-09-07 21:09 UTC, amauch-adobe approved these changes
Approved, revalidated mobile/tablet and everything looks good.

2022-09-08 18:22 UTC, auniverseaway approved these changes

2022-09-08 18:29 UTC, merged