MWPW-136885: More SEO-friendly, improved accessibility in merch cards
adobecom/milo pull request #1791
Opened 2024-01-26 03:05 UTC by Axelcureno

Programmatically replaces heading tag names in cascading order to improve SEO and accessibility in Merch cards.
The hierarchal order is the following:
- 1st heading: H3
- 2nd heading: H4
- 3rd heading: H5

_Note: No merch card should have more than 3 headings._

- 

Resolves: [MWPW-136885](https://jira.corp.adobe.com/browse/MWPW-136885)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card
- After: https://mwpw-136885--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card

2024-01-26 16:49 UTC, mirafedas approved these changes

2024-01-26 17:04 UTC, npeltier approved these changes

2024-01-26 17:04 UTC, npeltier commented on libs/blocks/merch-card/merch-card.js
> +  let headingCount = 3;
can we call it headingSize?

2024-01-26 17:04 UTC, npeltier commented on libs/blocks/merch-card/merch-card.js
> +  let headingCount = 3;
count sounds weird to me

2024-01-26 17:26 UTC, Axelcureno commented on libs/blocks/merch-card/merch-card.js
>    let bodySlotName = 'body-xs';
Thx, addressed.

2024-01-26 17:26 UTC, Axelcureno commented on libs/blocks/merch-card/merch-card.js
> +  let headingCount = 3;
Sure, it's done.

2024-01-26 18:23 UTC, Axelcureno commented on libs/blocks/merch-card/merch-card.js
> +        const newElement = createTag(tagName);
Fixed

2024-01-26 21:18 UTC, rgclayton commented
A few observations. 

If I author the title with an `<h> tag` other than `<h3>` the font size is different. The DOM is changed to an `<h3>` though if it's the first title, like your code says.

To me it seems like if you are going to the trouble to change the title element to something specific the font size should stay consistent? Or maybe that's expected? Seems odd. 

If I author with an `<h1>`, `<h5>` or `<h6>` the title is not rendered at all. Why not look for these so they at least render?


[Sample page](https://mwpw-136885--milo--axelcureno.hlx.page/drafts/rclayton/test/merch-card-testing) I test with.


![image](https://github.com/adobecom/milo/assets/2539954/6b58466f-a2df-423e-9fcb-ed8206caae59)

2024-01-26 22:18 UTC, Axelcureno commented
> A few observations.
> 
> If I author the title with an `<h> tag` other than `<h3>` the font size is different. The DOM is changed to an `<h3>` though if it's the first title, like your code says.
> 
> To me it seems like if you are going to the trouble to change the title element to something specific the font size should stay consistent? Or maybe that's expected? Seems odd.
> 
> If I author with an `<h1>`, `<h5>` or `<h6>` the title is not rendered at all. Why not look for these so they at least render?
> 
> [Sample page](https://mwpw-136885--milo--axelcureno.hlx.page/drafts/rclayton/test/merch-card-testing) I test with.
> 
> ![image](https://private-user-images.githubusercontent.com/2539954/300114826-6b58466f-a2df-423e-9fcb-ed8206caae59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMDc3MDEsIm5iZiI6MTcwNjMwNzQwMSwicGF0aCI6Ii8yNTM5OTU0LzMwMDExNDgyNi02YjU4NDY2Zi1hMmRmLTQyM2UtOWZjYi1lZDgyMDZjYWFlNTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjZUMjIxNjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWNhNDY5YmM4MjRkOTA1YmUyM2RhMDhlNmJlNjg0ZDc0OWY3MGI4MDJjZDc2NWMyMzg5MmRmYjBhNjA3ZWFlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GmSOF2YfuhVWW6VWSEma4tXePDrrbTRa3uq9WrwlH54)

@rgclayton thanks for the comment, you brought a good point. 
I started a discussion about it to make things easier for authors: https://github.com/orgs/adobecom/discussions/1799

2024-01-26 22:26 UTC, npeltier commented on libs/blocks/merch-card/merch-card.js
> +        const newElement = createTag(tagName);
does not look like it

2024-01-26 22:37 UTC, Axelcureno commented on libs/blocks/merch-card/merch-card.js
> +        const newElement = createTag(tagName);
Sorry, I got confused with the another comment.
I tried doing your suggestion, but it seems element.attributes returns a `NamedNodeMap` which is not compatible with `createTag()`.
![Screenshot 2024-01-26 at 2 36 25 PM](https://github.com/adobecom/milo/assets/1179549/ad1bef79-6a28-4854-86e6-cb6b96a5d222)

2024-01-29 09:51 UTC, npeltier requested changes
requesting discussion to be solved before going on :)

2024-02-12 17:05 UTC, vladen approved these changes

2024-02-12 18:01 UTC, VKniaz approved these changes

2024-02-16 06:43 UTC, npeltier approved these changes

2024-02-22 20:42 UTC, merged