Mwpw 142003: Mini Compare Chart card fixes
adobecom/milo pull request #2093
Opened 2024-03-28 23:58 UTC by Axelcureno

Third one is the charm...

Fixes multiple Mini Compare Chart card alignment and spacing issues.

Resolves: [MWPW-142003](https://jira.corp.adobe.com/browse/MWPW-142003)

**Test URLs:**
- Before: https://main--milo--axelcureno.hlx.page/drafts/axel/mini-compare-chart?martech=off
- After: https://mwpw-142003--milo--axelcureno.hlx.page/drafts/axel/mini-compare-chart?martech=off

2024-04-01 13:15 UTC, narcis-radu submitted a review, later dismissed
I am requesting changes since I have identified a couple of issues:
1. all browsers - you cannot tab anymore through clickable elements in the card
2. safari and firefox - in the 3rd card, there's a small overlapping between "Save 19% ($US7.99/mo) for the first year if you buy now" and "Secure transaction"
3. all browsers - mobile view is broken, the cards don't adjust width; the same issue is visible in the before link though.

2024-04-02 18:51 UTC, Axelcureno commented
> I am requesting changes since I have identified a couple of issues:
> 
> 1. all browsers - you cannot tab anymore through clickable elements in the card
> 2. safari and firefox - in the 3rd card, there's a small overlapping between "Save 19% ($US7.99/mo) for the first year if you buy now" and "Secure transaction"
> 3. all browsers - mobile view is broken, the cards don't adjust width; the same issue is visible in the before link though.

@narcis-radu thanks for the review, I have addressed the mentioned issues. The Test URL from my fork will not reflect the actual changes (alignment inside cards) because prices fail in milo-forked URLs. To see the changes with prices displaying properly please see https://main--cc--adobecom.hlx.page/drafts/axel/mini-compare-chart-edgecase?milolibs=MWPW-142003--milo--axelcureno
For testing mobile, this card has mobile-specific styles and height calculations triggered upon page load. Please refresh the page when testing in mobile. We decided not to trigger mobile view when the page is resized to avoid performance impact (since most users will not go from desktop to mobile in the same window).

2024-04-03 08:02 UTC, yesil approved these changes

2024-04-03 08:02 UTC, yesil commented on libs/blocks/merch-card/merch-offer-select.js
> +        description.parentNode.removeChild(description);
`description.remove();` should do it as well.

2024-04-03 12:29 UTC, narcis-radu commented
@Axelcureno - I still cannot tab through items when I use your feature branch. The #1 item from my initial feedback is still problematic.

2024-04-03 14:27 UTC, Axelcureno commented
> @Axelcureno - I still cannot tab through items when I use your feature branch. The #1 item from my initial feedback is still problematic.

@narcis-radu I forgot to mention, this is fixed in a separate ticket: https://github.com/adobecom/milo/pull/2078

2024-04-04 09:30 UTC, 3ch023 approved these changes

2024-04-08 22:57 UTC, Roycethan requested changes
@Axelcureno 
1)On mobile version the pricing text is "per" is broken in next line 
https://main--cc--adobecom.hlx.page/creativecloud?milolibs=MWPW-142003--milo--axelcureno
<img width="657" alt="image" src="https://github.com/adobecom/milo/assets/104928176/792b8173-0888-465e-95d5-42cda74e1da6">

2) Regarding CTA alignment its different in different page, which on'es correct?
https://main--cc--adobecom.hlx.page/creativecloud?milolibs=MWPW-142003--milo--axelcureno
<img width="608" alt="image" src="https://github.com/adobecom/milo/assets/104928176/3fa0e481-cfe9-4fcd-a994-4b14b65e1bdd">
https://main--cc--adobecom.hlx.page/products/premiere?milolibs=MWPW-142003--milo--axelcureno
<img width="421" alt="image" src="https://github.com/adobecom/milo/assets/104928176/314fa511-6cc0-4f31-b25a-6ddf5dee7efb">
3)'Best value' either should be in center align with product title or at top - plz review
https://main--cc--adobecom.hlx.page/creativecloud?milolibs=MWPW-142003--milo--axelcureno
<img width="399" alt="image" src="https://github.com/adobecom/milo/assets/104928176/9c4fd4fd-b068-40e1-ab4a-a8d8f83b30bd">
4)Strikethrough pricing font size is bit larger
https://main--cc--adobecom.hlx.page/creativecloud?milolibs=MWPW-142003--milo--axelcureno
<img width="384" alt="image" src="https://github.com/adobecom/milo/assets/104928176/1b49adf5-6feb-4376-a553-a7b7a4b6c388">

2024-04-09 00:04 UTC, Axelcureno commented
> @Axelcureno 1)On mobile version the pricing text is "per" is broken in next line https://main--cc--adobecom.hlx.page/creativecloud?milolibs=MWPW-142003--milo--axelcureno <img alt="image" width="657" src="https://private-user-images.githubusercontent.com/104928176/320668234-792b8173-0888-465e-95d5-42cda74e1da6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MjEyNjUsIm5iZiI6MTcxMjYyMDk2NSwicGF0aCI6Ii8xMDQ5MjgxNzYvMzIwNjY4MjM0LTc5MmI4MTczLTA4ODgtNDY1ZS05NWQ1LTQyY2RhNzRlMWRhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwMDAyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzJmYjEyYTBmNTdiNDY1ZWUwMzdhYjNlZDgyYzdiNGQ2ZjNiYTc0ZjAxZTMxYzg3N2ZiNzIyZGE0M2Y1MmFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._oZicpvVXPvCFGS78jSnVZlv5IWegEIW5F_UZcM4Fk8">
> 
> 2. Regarding CTA alignment its different in different page, which on'es correct?
>    https://main--cc--adobecom.hlx.page/creativecloud?milolibs=MWPW-142003--milo--axelcureno
> 
> <img alt="image" width="608" src="https://private-user-images.githubusercontent.com/104928176/320668531-3fa0e481-cfe9-4fcd-a994-4b14b65e1bdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MjEyNjUsIm5iZiI6MTcxMjYyMDk2NSwicGF0aCI6Ii8xMDQ5MjgxNzYvMzIwNjY4NTMxLTNmYTBlNDgxLWNmZTktNGZjZC1hOTk0LTRiMTRiNjVlMWJkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwMDAyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzY0MWYwMTU1ODgxNjA2N2NiMjY1MDE0YmJlMzRkZjEzODk0ZDIxNjkyZmQ0YTI4M2Q2MTMwMDEwN2Y1MTIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CdMRacoWxRPdzcOCmApDd0XQkey7fcdtv48878Ohekk"> https://main--cc--adobecom.hlx.page/products/premiere?milolibs=MWPW-142003--milo--axelcureno <img alt="image" width="421" src="https://private-user-images.githubusercontent.com/104928176/320668734-314fa511-6cc0-4f31-b25a-6ddf5dee7efb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MjEyNjUsIm5iZiI6MTcxMjYyMDk2NSwicGF0aCI6Ii8xMDQ5MjgxNzYvMzIwNjY4NzM0LTMxNGZhNTExLTZjYzAtNGYzMS1iMjVhLTZkZGY1ZGVlN2VmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwMDAyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2I0YTliN2UyOWMwM2ZkNzk3ZjZiZWU1NGRmZDkyOWQ5ZDJhNjU0MDViM2JlOTA0ODk1ZTI5MTdiZDVkODFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1Qub-MDeH1aZejUKmKWx9R3T3LETDlOgoRMXyTaSvF4"> 3)'Best value' either should be in center align with product title or at top - plz review https://main--cc--adobecom.hlx.page/creativecloud?milolibs=MWPW-142003--milo--axelcureno <img alt="image" width="399" src="https://private-user-images.githubusercontent.com/104928176/320668904-9c4fd4fd-b068-40e1-ab4a-a8d8f83b30bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MjEyNjUsIm5iZiI6MTcxMjYyMDk2NSwicGF0aCI6Ii8xMDQ5MjgxNzYvMzIwNjY4OTA0LTljNGZkNGZkLWIwNjgtNDBlMS1hYjRhLWE4ZDhmODNiMzBiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwMDAyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWYxMmVhMTQzMjBlNTA1YTU3NmMxZDQyODA4MDNhYjlmOGM1NWEwMzQ3OTgyYTdiZWVkZjEyNWFhYjdhNWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o81WpX87txoF8_q52nYn-yRCCGCvOkn29Fiu2HwD9ME"> 4)Strikethrough pricing font size is bit larger https://main--cc--adobecom.hlx.page/creativecloud?milolibs=MWPW-142003--milo--axelcureno <img alt="image" width="384" src="https://private-user-images.githubusercontent.com/104928176/320669308-1b49adf5-6feb-4376-a553-a7b7a4b6c388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MjEyNjUsIm5iZiI6MTcxMjYyMDk2NSwicGF0aCI6Ii8xMDQ5MjgxNzYvMzIwNjY5MzA4LTFiNDlhZGY1LTZmZWItNDM3Ni1hNTUzLWE3YjdhNGI2YzM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwMDAyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNmE4NGU1NTQ3MmI3YzQxYTgxMzc5M2RjZmE3Mzk4Y2M1NDliN2RkNzJlYzRiNGNhNDE2YTVlODI2ODZmOGE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a2SMilZlPMhn9wNjlrrZ-FUm-8UbWmpkG_5Ezx1M7-g">

I have addressed the mentioned comments @Roycethan, please check:

![Screenshot 2024-04-08 at 5 03 28 PM](https://github.com/adobecom/milo/assets/1179549/edd139b8-39cd-4790-a082-7284f8e4686a)
![Screenshot 2024-04-08 at 5 03 20 PM](https://github.com/adobecom/milo/assets/1179549/dce18c48-a04b-4eea-a6da-de135ba95161)
![Screenshot 2024-04-08 at 5 03 05 PM](https://github.com/adobecom/milo/assets/1179549/4dba5be8-1026-4ee8-bc11-8cc3a2abc31a)
![Screenshot 2024-04-08 at 5 02 51 PM](https://github.com/adobecom/milo/assets/1179549/70db1373-f56f-4d53-b257-e2d3315a9b26)

2024-04-09 01:52 UTC, Roycethan commented
> https://main--cc--adobecom.hlx.page/products/premiere?milolibs=MWPW-142003--milo--axelcureno

Thanks @Axelcureno 1,2,3 are fixed now

2024-04-09 01:58 UTC, Roycethan commented
Also observed one weird issue with quantity selector here: https://main--dc--adobecom.hlx.page/acrobat/features?milolibs=MWPW-142003--milo--axelcureno
4) On inner edit box theres up/down for increment/decrement when i use that the quanity is not getting applied to the Buy now CTA Href. although it works when using dropdown.
will loop @VKniaz  as well since he has worked on it before

fyi @afmicka

2024-04-09 02:00 UTC, Roycethan requested changes
@Axelcureno Plz check #4 above

2024-04-09 02:04 UTC, Axelcureno commented
> Also observed one weird issue with quantity selector here: https://main--dc--adobecom.hlx.page/acrobat/features?milolibs=MWPW-142003--milo--axelcureno 4) On inner edit box theres up/down for increment/decrement when i use that the quanity is not getting applied to the Buy now CTA Href. although it works when using dropdown. will loop @VKniaz as well since he has worked on it before <img alt="image" width="1080" src="https://private-user-images.githubusercontent.com/104928176/320697431-1d77237c-0550-47dc-85f2-9a4b936cf93e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MjgyNjMsIm5iZiI6MTcxMjYyNzk2MywicGF0aCI6Ii8xMDQ5MjgxNzYvMzIwNjk3NDMxLTFkNzcyMzdjLTA1NTAtNDdkYy04NWYyLTlhNGI5MzZjZjkzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwMTU5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjZmNjJhNjBmODhmNjhkYmIzNWVlZDI4NTViMzg4OTk3NWQzYTNlMjFlNmZmYWJhOWQ3NmYzNGVhMTUzZmE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6-xhDW74gFfS9PQ1Qqfozw0ud6ddLTs5iww2ZEeFgSA">
> 
> fyi @afmicka

> @Axelcureno Plz check 4 above

Thanks @Roycethan . Quantity selector issue is not related to this card but to the component itself. Will follow up offline to get browser details from your testing.

Regarding issue #4, strikethrough should be in normal font weight and smaller font size as per Consonant XD:

XD: 
<img width="450" alt="Screenshot 2024-04-08 at 7 03 30 PM" src="https://github.com/adobecom/milo/assets/1179549/5bd8de44-f6ad-422d-b4de-a1d7cfefcccd">


With PR changes: 
![Screenshot 2024-04-08 at 7 04 05 PM](https://github.com/adobecom/milo/assets/1179549/a77c3310-b505-471b-99b0-6b12432160ca)

2024-04-09 02:32 UTC, Roycethan commented
@Axelcureno  Tracking Quantity selector issue 4 in different ticket https://jira.corp.adobe.com/browse/MWPW-146254 since its also repro on hlx.live.

@afmicka when you get chance plz also do regressions around and then we can sign off cc @Axelcureno

2024-04-09 14:05 UTC, afmicka commented
@Axelcureno your changes are underlining links in the cards by default while on prod they underline on hover. Should that be like that? 
https://main--cc--adobecom.hlx.live/creativecloud/file-types/image?milolibs=MWPW-142003--milo--axelcureno&martech=off
<img width="762" alt="Screenshot 2024-04-09 at 16 02 04" src="https://github.com/adobecom/milo/assets/9551700/9d1bc045-a881-4d0b-b949-e282f5b5beac">

cc: @Roycethan

2024-04-09 14:11 UTC, afmicka commented
@Axelcureno not sure if i missed something in the requirements but shouldn't these be aligned and equal height as on prod?
https://mwpw-142003--milo--axelcureno.hlx.page/drafts/axel/mini-compare-chart?martech=off

<img width="1288" alt="Screenshot 2024-04-09 at 16 09 58" src="https://github.com/adobecom/milo/assets/9551700/c65abbe9-ef55-49e4-9fff-222c59e6a5b5">

2024-04-09 16:11 UTC, Axelcureno commented
> @Axelcureno not sure if i missed something in the requirements but shouldn't these be aligned and equal height as on prod? https://mwpw-142003--milo--axelcureno.hlx.page/drafts/axel/mini-compare-chart?martech=off
> 
> <img alt="Screenshot 2024-04-09 at 16 09 58" width="1288" src="https://private-user-images.githubusercontent.com/9551700/320878852-c65abbe9-ef55-49e4-9fff-222c59e6a5b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2Nzc5NzcsIm5iZiI6MTcxMjY3NzY3NywicGF0aCI6Ii85NTUxNzAwLzMyMDg3ODg1Mi1jNjVhYmJlOS1lZjU1LTQ5ZTQtOWZmZi0yMjJjNTllNmE1YjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMTU0NzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGExZjhhZTMzZmFkODc2NGQwMGFhYWMwYzNmMTVkYjZmYzVlNzE3OWE5MTIzNjM3MWM1NmM4YWMxN2VkNWYyNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.THu2jyO1nNWml1wLjmv3gTwv4t9wKQHer98sOTbLA1E">

Hi @afmicka, misalignment happens in my forked branch due to prices not loading. You can verify the alignment here: https://main--cc--adobecom.hlx.page/drafts/axel/mini-compare-chart-edgecase?milolibs=MWPW-142003--milo--axelcureno

> @Axelcureno not sure if i missed something in the requirements but shouldn't these be aligned and equal height as on prod? https://mwpw-142003--milo--axelcureno.hlx.page/drafts/axel/mini-compare-chart?martech=off
> 
> <img alt="Screenshot 2024-04-09 at 16 09 58" width="1288" src="https://private-user-images.githubusercontent.com/9551700/320878852-c65abbe9-ef55-49e4-9fff-222c59e6a5b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2Nzc5NzcsIm5iZiI6MTcxMjY3NzY3NywicGF0aCI6Ii85NTUxNzAwLzMyMDg3ODg1Mi1jNjVhYmJlOS1lZjU1LTQ5ZTQtOWZmZi0yMjJjNTllNmE1YjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMTU0NzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGExZjhhZTMzZmFkODc2NGQwMGFhYWMwYzNmMTVkYjZmYzVlNzE3OWE5MTIzNjM3MWM1NmM4YWMxN2VkNWYyNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.THu2jyO1nNWml1wLjmv3gTwv4t9wKQHer98sOTbLA1E">

About links underlined by default, Consonant requested this change for all cards. I just confirmed with them this morning:
![Screenshot 2024-04-09 at 9 11 09 AM](https://github.com/adobecom/milo/assets/1179549/876ebb88-35d8-4cff-b84a-3a32db73d558)

2024-04-09 16:47 UTC, afmicka commented
@Axelcureno prices are loaded with modheader on. I get that experience with prices on the page 

<img width="1044" alt="Screenshot 2024-04-09 at 18 47 30" src="https://github.com/adobecom/milo/assets/9551700/17c756e8-71fd-45ca-81f1-93fe1ff0adef">

2024-04-09 18:20 UTC, Roycethan requested changes
@Axelcureno Plz review this error , looks like overlapping causing 
<img width="1510" alt="image" src="https://github.com/adobecom/milo/assets/104928176/ab9f5afa-7528-4bbc-ae9d-77ca6db4810d">

2024-04-09 18:31 UTC, Roycethan commented
NLE fix, error is gone , but still see the price-stotage overlapping :

2024-04-11 14:17 UTC, Axelcureno commented
> NLE fix, error is gone , but still see the price-stotage overlapping on 3rd card : <img alt="image" width="1460" src="https://private-user-images.githubusercontent.com/104928176/320964256-0bcbf640-ec64-419e-aee4-38ee2b1c92cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDUzMDAsIm5iZiI6MTcxMjg0NTAwMCwicGF0aCI6Ii8xMDQ5MjgxNzYvMzIwOTY0MjU2LTBiY2JmNjQwLWVjNjQtNDE5ZS1hZWU0LTM4ZWUyYjFjOTJjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxNDE2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjkzYjczMjM2ZDQ2YjYzZTRlNzQ5NTkyOTYyODJkYmE1NmM1ZDZjM2Q4N2FmNjVhZGVhYmQxNzExMGViMjc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5whLyRC_u1ulM_2rxIdyNt1I1dVp6oYnpnwF4QGU6oA">

The issue has been fixed, please check again 🙏🏼 @Roycethan @afmicka

2024-04-11 18:38 UTC, Roycethan requested changes
<img width="1109" alt="image" src="https://github.com/adobecom/milo/assets/104928176/a3dc44eb-adb2-4f90-8c30-7a3d21caba12">
On latest https://main--cc--adobecom.hlx.page/drafts/axel/mini-compare-chart?milolibs=mwpw-142003--milo--axelcureno

2024-04-12 03:55 UTC, Roycethan commented
@Axelcureno The overlapping of pricing is fixed now on both desktop/mobile . Badge padding around is adjusted.
Storage options are stcked one below other as per XD which fixed the padding issue.
One outstanding issue which i still see on mobile is mis-alignment of CTA's and other components:
<img width="716" alt="image" src="https://github.com/adobecom/milo/assets/104928176/8d17d70a-afc8-4295-bda2-dc147119581a">

2024-04-12 17:13 UTC, Roycethan commented
@yesil @Axelcureno Links that have this issue are: 
https://main--cc--adobecom.hlx.page/drafts/axel/mini-compare-chart-edgecase?milolibs=MWPW-142003--milo--adobecom
https://main--cc--adobecom.hlx.page/drafts/axel/mini-compare-chart?milolibs=mwpw-142003--milo--axelcureno

2024-04-16 01:26 UTC, Roycethan requested changes
@Axelcureno  The mis-alignment on Mobile issue is fixed on latest commit.Thanks.
On a side note can you plz check why this pricing font is having font H4 , its expected as h2 there...
https://mwpw-142003--milo--axelcureno.hlx.page/docs/library/kitchen-sink/merch-card?martech=off
cc @afmicka 
<img width="322" alt="image" src="https://github.com/adobecom/milo/assets/104928176/25e73f8a-20f3-4712-aa3c-11d2f8a4857c">

2024-04-16 12:24 UTC, robert-bogos commented
Hi @Axelcureno! I see that some unit tests are failing 🤔

2024-04-17 18:46 UTC, Axelcureno commented
> @Axelcureno The mis-alignment on Mobile issue is fixed on latest commit.Thanks. On a side note can you plz check why this pricing font is having font H4 ans font size is bit bigger 24 px https://mwpw-142003--milo--axelcureno.hlx.page/docs/library/kitchen-sink/merch-card?martech=off cc @afmicka plz do some more regressions <img alt="image" width="322" src="https://private-user-images.githubusercontent.com/104928176/322670669-25e73f8a-20f3-4712-aa3c-11d2f8a4857c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNzk0ODUsIm5iZiI6MTcxMzM3OTE4NSwicGF0aCI6Ii8xMDQ5MjgxNzYvMzIyNjcwNjY5LTI1ZTczZjhhLTIwZjMtNDcxMi1hYTNjLTExZDJmOGE0ODU3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxODM5NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YWJkZDU5MWM2MzZhMDExZjlkMmMwMDVjOWUxNDEyZTQ0YzZkZWYzMWZkYmJmOTVjNzljMjEwOTUwMjIzZWM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KULyUAP9vpLXokQ-m81uZlXoGFpbArNhBc9SEasDChM">

@Roycethan 24px font size is correct for this card:
We moved away from using H2s inside merch cards because it hurts accessibility and SEO. There was a ticket for this change. Now, merch cards use headings in a descending hierarchal order starting fro H3.
![Screenshot 2024-04-17 at 11 42 39 AM](https://github.com/adobecom/milo/assets/1179549/8047af5b-9659-4555-b81b-c8f656ac5ed1)

2024-04-18 04:58 UTC, Roycethan requested changes
@Axelcureno 
1) On latest - the secure transaction label is mis-aligned on all cards
https://mwpw-142003--milo--axelcureno.hlx.page/docs/library/kitchen-sink/merch-card?martech=off
https://main--cc--adobecom.hlx.page/drafts/axel/mini-compare-chart?milolibs=mwpw-142003--milo--axelcureno
<img width="1024" alt="image" src="https://github.com/adobecom/milo/assets/104928176/0b2dbe30-7064-4479-96e8-12fb6af44814">
<img width="594" alt="image" src="https://github.com/adobecom/milo/assets/104928176/d63b9aba-a79c-4060-8e09-6f252f05edaf">
<img width="394" alt="image" src="https://github.com/adobecom/milo/assets/104928176/9a0a00f6-99e6-4cfc-b868-281ce2a5c0d4">

2)For segment card i don't see left/right padding and the margin touching the border in Mobile viewport
https://mwpw-142003--milo--axelcureno.hlx.page/docs/library/kitchen-sink/merch-card?martech=off
<img width="630" alt="image" src="https://github.com/adobecom/milo/assets/104928176/af7f0ea9-4756-41df-9388-f68dac36f426">

3) Badge is overlapping the tile in mobile:
https://main--cc--adobecom.hlx.page/creativecloud?milolibs=MWPW-142003--milo--axelcureno
<img width="800" alt="image" src="https://github.com/adobecom/milo/assets/104928176/1db6a346-1fe8-44ed-9249-189c5f951965">

4) On tablet view the CTA's are mis aligned in Business tab:
https://main--dc--adobecom.hlx.page/acrobat/features?milolibs=MWPW-142003--milo--axelcureno
<img width="1151" alt="image" src="https://github.com/adobecom/milo/assets/104928176/894e29fa-1a85-4e06-891f-992bc8168aa1">

5)Two cards on mobile/tablet upper border is touching the tab paddles
https://main--cc--adobecom.hlx.page/products/premiere?milolibs=MWPW-142003--milo--axelcureno
<img width="833" alt="image" src="https://github.com/adobecom/milo/assets/104928176/3de73a95-acc3-4cb0-a086-502871aef222">



fyi @afmicka

2024-04-18 22:07 UTC, Roycethan approved these changes
Issue mentioned above related to this PR are fixed, for few created separate tickets since they are not related to this PR and exist in main. Few other issues noted while doing regressions are also fixed. Marking as verified since this urgent request and continue testing, and if theres anything comes up will create separate ticket.
@Axelcureno  cc @afmicka

2024-04-19 15:35 UTC, Axelcureno commented
> This PR has changes requested from @narcis-radu - this cant be merged with changes requested and thus isn't ready for stage.

@narcis-radu as per our requirements, tab click is to navigate within inner clickable elements of a merch card and arrow keys to navigate between cards. You may check this functionality in the test URL. 
This PR is getting escalated because it's blocking important CC and DC migrations.

cc @yesil @mokimo @npeltier

2024-04-19 23:25 UTC, Axelcureno commented
As [confirmed by PdMs](https://adobe-mwp.slack.com/archives/CCB79168Z/p1713564451972099), the requested changes by @narcis-radu are not in accord with our requirements, hence adding Ready for Stage label.

For any questions, please reach out to April Burness, Lucy Sogard or Nick Lam.
cc @mokimo @npeltier @yesil @3ch023

2024-04-22 08:51 UTC, drashti1712 commented
Hi @Axelcureno 
The `aem-psi-check` is failing for this PR. Could you please take a look at it?

2024-04-22 17:04 UTC, Axelcureno commented
> Hi @Axelcureno The `aem-psi-check` is failing for this PR. Could you please take a look at it?

Thank you, I have retriggered and it is now passing all checks :)

2024-04-22 17:28 UTC, merged