Mepparamtarget
adobecom/milo pull request #2119
Opened 2024-04-08 19:51 UTC by vgoodric

Steps to reproduce:
1. Create a manifest
3. Create a page that references that manifest in its personalization metadata
4. Create a Target activity that serves the same manifest to the page
5. Update the manifest to have a new column but don't update the Target offer
6. Try to use the MEP button to spoof the new column

Example page setup that is sending an old version of manifest via Target and is trying to spoof a new column not sent by Target:
 - Before: https://main--cc--adobecom.hlx.page/drafts/vgoodrich/fragments/2024/q2/mepparamtarget/?at_preview_token=vq2HGezS8xc9gv4--gb5Ug&at_preview_index=1_1&at_preview_listed_activities_only=true&mep=%2Fdrafts%2Fvgoodrich%2Ffragments%2F2024%2Fq2%2Fmepparamtarget%2Fmanifest.json--photoshop-any
 -  After: https://main--cc--adobecom.hlx.page/drafts/vgoodrich/fragments/2024/q2/mepparamtarget/?milolibs=mepparamtarget&at_preview_token=vq2HGezS8xc9gv4--gb5Ug&at_preview_index=1_1&at_preview_listed_activities_only=true&mep=%2Fdrafts%2Fvgoodrich%2Ffragments%2F2024%2Fq2%2Fmepparamtarget%2Fmanifest.json--photoshop-any

Resolves: [MWPW-145303](https://jira.corp.adobe.com/browse/MWPW-145303)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/?martech=off
- After: https://mepparamtarget--milo--adobecom.hlx.page/?martech=off

2024-04-09 07:52 UTC, afmicka commented
@vgoodric these changes are breaking preview functionality (and our promo nala tests, thats why it was not passing. We have added those tests recently so please do not skip run-nala label). If you go to the url below and try to set to default any of the manifests and preview, it will not go through. It reloads again with all the manifests set to all. 
https://mepparamtarget--milo--adobecom.hlx.live/drafts/nala/features/promotions/promo-default
<img width="360" alt="Screenshot 2024-04-09 at 09 40 20" src="https://github.com/adobecom/milo/assets/9551700/6163cf21-9514-4036-a77f-5d4eccfe3258">
<img width="380" alt="Screenshot 2024-04-09 at 09 40 12" src="https://github.com/adobecom/milo/assets/9551700/6673ad83-2451-46b1-9c8b-7f763d3c3fb2">


It works on: https://main--milo--adobecom.hlx.live/drafts/nala/features/promotions/promo-default

Could you please review? 

cc: @nateekar

2024-04-09 18:23 UTC, chrischrischris approved these changes

2024-04-09 19:06 UTC, afmicka requested changes
Please review MEP preview functionality on existing pages with multiple manifests like UK acom homepage as well. The changes are breaking it there too.

https://main--homepage--adobecom.hlx.page/uk/homepage/index-loggedout?milolibs=mepparamtarget

2024-04-09 23:45 UTC, vgoodric commented
@afmicka I turned off nala because there was something broken on stage as well.  So it wasn't instructive.  But I think everything is working now.  Can you confirm?

2024-04-10 01:29 UTC, mokimo approved these changes

2024-04-10 01:29 UTC, mokimo commented on libs/features/personalization/personalization.js
> +  }
I'd avoid the nested if elses
```suggestion
  if (!selectedVariant) return
  if (variantNames.includes(selectedVariant)) {
    manifest.selectedVariantName = selectedVariant;
    manifest.selectedVariant = manifest.variants[selectedVariant];
    return
  } 
  manifest.selectedVariantName = selectedVariant;
  manifest.selectedVariant = manifest.variants[selectedVariant];
```

2024-04-10 07:41 UTC, afmicka commented
> @afmicka I turned off nala because there was something broken on stage as well. So it wasn't instructive. But I think everything is working now. Can you confirm?

Thanks @vgoodric. Confirming it is ok now.

2024-04-10 23:51 UTC, Blainegunn commented
@vgoodric no verified label. Please add

2024-04-10 23:53 UTC, merged