MWPW-147127 Scrolling on the gnav in mobile portrait and landscape view is not working as expected ,navigation menu when opened is not seen rendered completely in MILO Pages
adobecom/milo pull request #2185
Opened 2024-04-23 11:46 UTC by sharmrj

The content in the gnav menu (in mobile/tablet viewports, when it's open) was being cut-off on the bottom due to an incorrect height value in the wrapper. Correcting the height value for the wrapper in non desktop viewports fixes the issue

Resolves: [MWPW-147127](https://jira.corp.adobe.com/browse/MWPW-147127)

**Test URLs:**

Before: https://main--milo--adobecom.hlx.page?martech=off
After: https://mobile-gnav--milo--sharmrj.hlx.page?martech=off
  
Before: https://main--cc--adobecom.hlx.page/creativecloud?martech=off
After: https://main--cc--adobecom.hlx.live/creativecloud?milolibs=mobile-gnav--milo--sharmrj&martech=off

2024-04-23 12:22 UTC, narcis-radu commented
Please provide a testing URL

2024-04-23 14:46 UTC, overmyheadandbody commented on libs/blocks/global-navigation/global-navigation.css
> +  height: calc(100vh - var(--feds-height-nav));
There might be promos or other elements on top of the gnav, there's padding logic that should be handling this. Please add some screenshots and some valid test URLs so we can better understand what you're trying to fix.

2024-04-23 16:29 UTC, overmyheadandbody requested changes
The issue is actually here - https://github.com/adobecom/milo/blob/stage/libs/blocks/global-navigation/global-navigation.js#L658-L664

The logic that adds padding is no longer being called, that should be investigated.

Just subtracting the height does not cover all the use cases. Breadcrumbs count towards height. Eventual Promos on top of the nav count towards height. That's why it needs to be calculated on the fly. Figuring out what happened to the logic I've referenced at the top should handle all these use-cases.

2024-04-24 02:23 UTC, sharmrj commented
I've tested on https://main--cc--adobecom.hlx.live/creativecloud?milolibs=mobile-gnav--milo--sharmrj&martech=off

You're right . I was under the impression that `setHamburgerPadding` was being called but was accounting for items above it (I misinterpreted the bottom). The problem was in `await loadSearch`, which was throwing an error that was caught elsewhere (and the error is lana logged so it doesn't appear on the console), so execution was never returned to our bit of code. I imagine we might need to log this error or should the catch I put in be empty as it is now? I think we don't use search anywhere currently (?) so is the error in loading search a problem?
The padding is set only after we close the hamburger for the first time, not when we open it for the first time (this is in the original logic, prior to #2184 being merged into stage), so I've changed that. Should I add some logic so we don't get needless repeat invocations of this method? The padding being removed in the desktop check is overridden by a `padding: 0 !important` in the min-width: 900px media query, do we want both?

2024-04-24 10:34 UTC, mokimo commented
@sharmrj The mention about search is a great one - it might be that we are able to get rid of it completely. That would deserve a due diligence story and checking if any consumers still use it.

Blog currently uses a search variation, but they also use the old gnav and an incompatible search

2024-04-25 02:44 UTC, sharmrj commented
I've added [MWPW-147270](https://jira.corp.adobe.com/browse/MWPW-147270) as a followup

2024-05-07 09:28 UTC, spadmasa commented
Verified the changes on below url :
https://main--cc--adobecom.hlx.live/creativecloud?milolibs=mobile-gnav--milo--sharmrj
![image](https://github.com/adobecom/milo/assets/73129464/4dd12548-3131-45ab-b2cf-b060ae189197)
![image](https://github.com/adobecom/milo/assets/73129464/cbafc9e2-5236-45b1-b4ee-26821048cc8c)
![image](https://github.com/adobecom/milo/assets/73129464/894887d6-e1cb-483e-ae5d-d852251f9408)

2024-05-10 00:39 UTC, merged