spectrum picker and chevron icon added
adobecom/milo pull request #2277
Opened 2024-05-08 15:07 UTC by draganatrajkovic

From spectrum components added:
* sp-picker
* sp-icon-chevron100
* sp-icon-chevron-down

**Test URLs:**
- Before:  https://partner-news-block--dx-partners--adobecom.hlx.page/SPP/drafts/dragana/partner-news?martech=off
- After:  https://partner-news-block--dx-partners--adobecom.hlx.page/SPP/drafts/dragana/partner-news?milolibs=spectrum-picker-and-chevron-icon--milo--draganatrajkovic&martech=off

2024-05-10 08:12 UTC, yesil commented on libs/features/spectrum-web-components/src/icons-ui.js
> +import '@spectrum-web-components/icons-ui/icons/sp-icon-chevron100.js';
please follow alphabetical order.

2024-05-10 08:12 UTC, yesil commented on libs/features/spectrum-web-components/src/icons-workflow.js
> +import '@spectrum-web-components/icons-workflow/icons/sp-icon-chevron-down.js';
please follow alphabetical order.

2024-05-10 08:59 UTC, draganatrajkovic commented on libs/features/spectrum-web-components/src/icons-ui.js
> +import '@spectrum-web-components/icons-ui/icons/sp-icon-chevron100.js';
Thank you, i pushed fix

2024-05-10 08:59 UTC, draganatrajkovic commented on libs/features/spectrum-web-components/src/icons-workflow.js
> +import '@spectrum-web-components/icons-workflow/icons/sp-icon-chevron-down.js';
Thank you, this is also resolved

2024-05-13 13:00 UTC, mokimo approved these changes

2024-05-13 15:06 UTC, yesil requested changes
@draganatrajkovic can you include package-lock.json please?

Also, as per the doc, can you add a simple test?

2024-05-14 14:31 UTC, Ben-Zahler commented
@yesil @mokimo we have an unfortunate situation here: the spectrum web component is not working on mobile yet and it seems to be tricky to get it to work reliably (@draganatrajkovic and @saragajic11 tried to import additional dependencies such as "tray", this works 33% of the time).
Furthermore, the mobile behaviour for the "picker" is different than our [reference implementation](https://business.adobe.com/customer-success-stories.html), a tray slides out at the bottom of the screen in the spectrum web component:
<img width="393" alt="image" src="https://github.com/adobecom/milo/assets/3941815/196e1636-1ab6-45cd-8443-d8459d6188c9">
Everyone in our team thinks the reference implementation provides the better UX.
So we suggest that we close this PR and implement this as per our reference ourselves. Are you ok with this? Or do you see any benefit in adding the "picker" to milo even if we do not need it?

2024-05-14 16:51 UTC, yesil commented
@Ben-Zahler before a final decision, I would reach out to SWC team(they are very helpful) at `#spectrum-web-components` and ask their feedback on the topic.
if you need support on the Milo SWC version, let me know, I can try to help there.

2024-05-17 13:26 UTC, draganatrajkovic commented
@yesil @mokimo 
Thank you. 
After sync up with our designer we decided not to use picker from spectrum web components.
Therefore I will close this pr.

2024-05-17 13:27 UTC, closed without merging

2024-05-17 13:28 UTC, Ben-Zahler commented
@yesil FYI: spectrum web components team did respond quickly in Slack, but the answer is that this is a design request and our designer would have to raise it with the spectrum design team -> after all, the process just seemed to be too complicated for the relatively simple thing we need to implement ourselves.