OPT-26580 DC0994_US | Frictionless | Add sticky banner Upload CTA
adobecom/milo pull request #2298
Opened 2024-05-13 20:31 UTC by ivanvatadobe

POC for addition to sticky banner on frictionless pages. Mimicking behavior of a button that can interact and start the widget. Using javascript function to achieve the simulated click, but is not the plan for the final feature. The final feature will likely be built by the eng team that builds the frictionless widgets. 

Resolves: [OPT-26580](https://jira.corp.adobe.com/browse/OPT-26580)

**Test URLs for psi check:**
- Before: https://main--milo--adobecom.hlx.page/?martech=off
- After: https://dc0944stickybanner--milo--adobecom.hlx.page/?martech=off

**Test URLs to view feature:**
- Before: https://main--dc--adobecom.hlx.page/drafts/viloria/fragments/dc0994/testercompresspage?mep=%2Fdc-shared%2Ffragments%2Ftests%2F2024%2Fq2%2Fdc0944%2Fdc0944.json--target-var1-insidewrapper&mepButton=off
- After: https://main--dc--adobecom.hlx.page/drafts/viloria/fragments/dc0994/testercompresspage?mep=%2Fdc-shared%2Ffragments%2Ftests%2F2024%2Fq2%2Fdc0944%2Fdc0944.json--target-var1-insidewrapper&milolibs=dc0944stickybanner&mepButton=off

2024-05-13 21:30 UTC, vgoodric commented
For CSS, switch to using `.aside.frictionless` instead of `.section.hide-on-step-start` unless needed.

2024-05-13 21:32 UTC, vgoodric requested changes
Please see comments

2024-05-13 21:32 UTC, vgoodric commented on libs/mep/dc0944/aside/aside.js
> +        }
```suggestion
        window.scrollTo(0, 0);
        document.querySelector('.CTAButtons')?.click();
```

2024-05-13 21:32 UTC, vgoodric commented on libs/mep/dc0944/aside/aside.js
> +        }
Think this can be reduced to less lines.

2024-05-14 09:02 UTC, robert-bogos commented on libs/mep/dc0944/aside/aside.js
> +    if (moduleCtas.length) {
Nit: Same here, we can skip the caching
```suggestion
    if (document.querySelectorAll('.CTAButtons').length) {
```

2024-05-14 16:59 UTC, ivanvatadobe commented on libs/mep/dc0944/aside/aside.js
> +}
Although these files look like they are completely new code, they're actually just experimental/temporary copies for an upcoming test. 

I do not feel comfortable committing this change as I did not change the original for my test version.

2024-05-14 17:00 UTC, ivanvatadobe commented on libs/mep/dc0944/aside/aside.js
> +  decorateBlockText(blockText, blockData);
I do not feel comfortable committing this change as I did not change the original for my test version.

2024-05-14 17:27 UTC, ivanvatadobe commented on libs/mep/dc0944/aside/aside.js
> +}
Change added.

2024-05-15 14:28 UTC, ivanvatadobe commented
@vgoodric I have made a single CSS update as a response to QA testing on milo preview pages. 

The changes are committed and pushed. There are no other requests from QA.

2024-05-15 16:27 UTC, rgclayton commented
Why is this being submitted to the Milo repo? Shouldn't this POC code live under DC's repo?

cc: @vgoodric

2024-05-15 16:40 UTC, vgoodric approved these changes

2024-05-15 16:45 UTC, vgoodric commented
> POC code live under DC

@rgclayton This on the Milo repo because it's using a version of aside for the test.  It's quarantined to the MEP folder, so it doesn't really matter which repo it's on and it's easier to use the same repo that the block you're copying is also on.  Less updates to the code.

2024-05-15 17:26 UTC, denlight approved these changes

2024-05-16 11:55 UTC, merged