MWPW-147601: sending ML field text to Analytics
adobecom/milo pull request #2334
Opened 2024-05-20 16:00 UTC by JackySun9

* sending user prompts in ML field to Adobe Analytics

Resolves: [MWPW-147601](https://jira.corp.adobe.com/browse/MWPW-147601)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/quiz/quiz-entry/?martech=off
- After: https://stage--milo--jackysun9.hlx.page/drafts/quiz/quiz-entry/?martech=off&debug=quiz-entry

How to test:
1. use debug link: https://stage--milo--jackysun9.hlx.page/drafts/quiz/quiz-entry/?martech=off&debug=quiz-entry
2. check network log with filter "/ee"
3. You can also check the sending value in console log
<img width="1657" alt="Screenshot 2024-05-20 at 8 47 35 AM" src="https://github.com/adobecom/milo/assets/67350368/a5172a86-fc32-44d2-b48d-a8a0475b39b7">

<img width="606" alt="Screenshot 2024-05-20 at 9 00 28 AM" src="https://github.com/adobecom/milo/assets/67350368/bdc4c9aa-9563-4e69-ae56-f8e8765cedb6">

2024-05-20 16:41 UTC, fullcolorcoder requested changes

2024-05-20 16:41 UTC, fullcolorcoder commented on libs/blocks/quiz-entry/quiz-entry.js
> +  const sendMLFieldTextAnalytics = (fieldText) => {
Missing test coverage.

2024-05-21 04:29 UTC, JackySun9 commented
@fullcolorcoder Unit tests will be added in the user story: https://jira.corp.adobe.com/browse/MWPW-149369

2024-05-21 19:56 UTC, colloyd approved these changes

2024-05-21 20:45 UTC, fullcolorcoder approved these changes

2024-05-21 20:56 UTC, jedjedjedM approved these changes

2024-05-22 00:39 UTC, merged