MWPW-149470[MILO][MEP] Remove sendTargetResponseAnalytics function
adobecom/milo pull request #2371
Opened 2024-05-24 17:26 UTC by markpadbe

Remove function temporarily added to collect analytics data

to check the effect of the code change, filter the network tab for the word "collect".  The current code sends an event with the timeout information.  The new code does not.

Resolves: [MWPW-149470](https://jira.corp.adobe.com/browse/MWPW-149470)

**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q2/meppznanalytics/pzn-and-target
- After: https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q2/meppznanalytics/pzn-and-target?milolibs=remove-sendtargetresponseanalytics

2024-05-27 09:16 UTC, mokimo approved these changes

2024-05-27 11:56 UTC, overmyheadandbody approved these changes

2024-05-27 13:06 UTC, robert-bogos approved these changes

2024-06-10 13:32 UTC, robert-bogos requested changes
@markpadbe There are some conflicts with Stage, can you please look into that?

2024-06-10 21:54 UTC, closed without merging