Mwpw 141119: Change default pricing for Africa site to fix broken prices/promos
adobecom/milo pull request #2500
Opened 2024-06-22 04:40 UTC by rahulgupta999

Updated mapping for Africa region to en_MU (Mauritius) 

Resolves: [MWPW-141119](https://jira.corp.adobe.com/browse/MWPW-141119)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/africa/drafts/mili/promo-placeholders 
- After: https://mwpw-141119--milo--rahulgupta999.hlx.page/africa/drafts/mili/promo-placeholders

2024-06-24 10:12 UTC, 3ch023 requested changes
All good with PR, requesting changes just to delay the merge to the specific go-live date:
Tentatively targeting July 17

2024-07-16 14:13 UTC, 3ch023 requested changes
commerce.js is missing branch/commit line
could you please re-generate with 'npm run build:milo'

2024-07-16 15:46 UTC, 3ch023 approved these changes

2024-07-18 12:29 UTC, narcis-radu approved these changes

2024-07-18 12:31 UTC, mokimo approved these changes

2024-07-18 17:10 UTC, merged