MWPW-154054: Blank space between marquee and medium promo bar
adobecom/milo pull request #2582
Opened 2024-07-17 11:00 UTC by mirafedas

When inserting an anchor link for the delayed modal we need to hide not only the link itself but the wrapping <p> element, otherwise it brings unwanted blank space.

Resolves: [MWPW-154054](https://jira.corp.adobe.com/browse/MWPW-154054)

**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/products/aftereffects/free-trial-download?instant=2024-08-19T14:00:00.000Z
- After: https://main--cc--adobecom.hlx.page/products/aftereffects/free-trial-download?instant=2024-08-19T14:00:00.000Z&milolibs=MWPW-154054-blank-space--milo--mirafedas

2024-07-17 11:27 UTC, 3ch023 commented on libs/features/personalization/personalization.js
> +  const isDelayedModalAnchor = /#.*delay=/.test(href);
could you add a test case for it in personalization.js please? that it adds 'hide-block' class

2024-07-17 11:28 UTC, 3ch023 requested changes
please add a test case in unit tests for this

2024-07-17 13:56 UTC, mirafedas commented on libs/blocks/modal/modal.js
> -  el.classList.add('hide-block');
That does not exist, the delayed modal may be added only in the promo manifest

2024-07-17 17:08 UTC, Axelcureno commented
Please sync with stage to have NALA tests pass @mirafedas

2024-07-18 08:13 UTC, narcis-radu commented on libs/features/personalization/personalization.js
> +  if (isDelayedModalAnchor) {
```suggestion
  if (isDelayedModalAnchor) frag.classList.add('hide-block');
```

2024-07-18 10:56 UTC, 3ch023 approved these changes

2024-07-18 15:40 UTC, chrischrischris approved these changes

2024-07-18 15:58 UTC, narcis-radu approved these changes

2024-07-18 16:00 UTC, Axelcureno approved these changes

2024-07-18 17:07 UTC, merged

2024-07-18 17:08 UTC, mokimo commented
Disregard the last message fixed by https://github.com/adobecom/milo/pull/2581