MWPW-153245 [merch][analytics] dispatch wcomp events, and let default lh
adobecom/milo pull request #2610
Opened 2024-07-23 13:57 UTC by npeltier

- dispatch merch wc shadow event for analytics,
- if lh attribute is already set, keep it, appending eventually mep information,
- also remove merch-sidenav dependency that is only consumed in CC atm,

Resolves: [MWPW-136881](https://jira.corp.adobe.com/browse/MWPW-136881)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/?martech=off
- After: https://mwpw-153245--milo--npeltier.hlx.live/?martech=off

- Before: https://main--cc--adobecom.hlx.live/products/catalog
- After: https://mwpw-153245--cc--npeltier.hlx.live/products/catalog?milolibs=mwpw-153245--milo--npeltier

2024-07-23 15:12 UTC, npeltier commented
no "need" to resolve conflicts right now, as dep will be overwritten one last time once first approvals are made

2024-07-23 16:55 UTC, Axelcureno approved these changes

2024-07-23 17:35 UTC, chrischrischris commented on libs/martech/attributes.js
> +    if (!lhAtt) {
nit: reverse if/else: `if (lhAtt) {`

2024-07-23 17:36 UTC, chrischrischris approved these changes

2024-07-23 20:19 UTC, vgoodric requested changes

2024-07-23 20:19 UTC, vgoodric commented on libs/martech/attributes.js
> +    }
```suggestion
    let lhAtt = block.getAttribute('daa-lh');
    if (!lhAtt) {
      const blockName = block.classList[0] || '';
      lhAtt = `b${blockIdx + 1}|${blockName.slice(0, 15)}`;
    }
    block.setAttribute('daa-lh', `${lhAtt}${mepMartech}`);
    decorateDefaultLinkAnalytics(block, config);
```
Need to keep decorateDefaultLinkAnalytics outside of the if statement.  And I think this suggestion is cleaner.

2024-07-23 20:30 UTC, Roycethan commented
@npeltier Can you plz review below:
1) Sort:Popularity event name is "authored--:sort|s2|all|nopzn|catalog-devicet" doesn't have keyword Popularity
2) Hover over action menu click on any card generates same event name without any product name i.e. 
"merch-card:action-menu-toggle|s2|all|nopzn|catalog-devicet"

2024-07-24 15:53 UTC, npeltier commented
@Roycethan can you have a second look? (not sure why but search related network call happens much after it, but still does)

2024-07-24 16:16 UTC, Roycethan commented
> @npeltier Can you plz review below:
> 
> 1. Sort:Popularity event name is "authored--:sort|s2|all|nopzn|catalog-devicet" doesn't have keyword Popularity
> 2. Hover over action menu click on any card generates same event name without any product name - for all the product cards i.e.
>    "merch-card:action-menu-toggle|s2|all|nopzn|catalog-devicet"
> 3. Search box - search doesn't triggered any events
> 4. Show more button not triggering analytics events - can be checked at https://main--cc--adobecom.hlx.live/products/catalog?milolibs=mwpw-153245--milo--npeltier#category=all
> 5. Product icon in the card which is clickable , same case with product name -
>    6)Learn more (link) - has daa-ll , but event name is not populated
> 
> Apart from above observation/issues , covered regressions.

@npeltier 1,2,4 are fixed... 3 ,5,6 are open

2024-07-24 16:29 UTC, vgoodric approved these changes
Checked the update.  Looks good to me

2024-07-24 17:13 UTC, Roycethan commented
> > @npeltier Can you plz review below:
> > 
> > 1. Sort:Popularity event name is "authored--:sort|s2|all|nopzn|catalog-devicet" doesn't have keyword Popularity
> > 2. Hover over action menu click on any card generates same event name without any product name - for all the product cards i.e.
> >    "merch-card:action-menu-toggle|s2|all|nopzn|catalog-devicet"
> > 3. Search box - search doesn't triggered any events
> > 4. Show more button not triggering analytics events - can be checked at https://main--cc--adobecom.hlx.live/products/catalog?milolibs=mwpw-153245--milo--npeltier#category=all
> > 5. Product icon in the card which is clickable , same case with product name -
> >    6)Learn more (link) - has daa-ll , but event name is not populated
> > 
> > Apart from above observation/issues , covered regressions.
> 
> @npeltier 1,2,4,5,6 are fixed... 3 is fixed

2024-07-25 09:15 UTC, merged