[MWPW-152181] Tabbing gets "stuck" after second instance of merch-card CTAs, within a segment blade
adobecom/milo pull request #2650
Opened 2024-07-30 08:53 UTC by rohitsahu

Allow the default tab action to proceed if the current focused element is from the last merch card.

Resolves: [MWPW-152181](https://jira.corp.adobe.com/browse/MWPW-152181)

Test URLs:
Before: https://main--milo--adobecom.hlx.page/drafts/rosahu/rosahu
After: https://mwpw-152181-2--milo--rohitsahu.hlx.page/drafts/rosahu/rosahu

2024-07-30 09:30 UTC, mokimo approved these changes

2024-07-30 12:48 UTC, 3ch023 requested changes
Hi @rosahu /libs/features/mas/* are source files, you need to include also generated dependencies. pages are loading files from /deps/mas/*, so those should be updated and included in the PR

```
cd libs/features/mas 
npm run build
```

should do the trick.
I noticed that from /web-components 'npm run build' seems to not work properly, maybe you could fix that? but it's an optional request.

2024-07-30 14:07 UTC, rohitsahu commented
> Hi @RosaHu /libs/features/mas/* are source files, you need to include also generated dependencies. pages are loading files from /deps/mas/*, so those should be updated and included in the PR
> 
> ```
> cd libs/features/mas 
> npm run build
> ```
> 
> should do the trick. I noticed that from /web-components 'npm run build' seems to not work properly, maybe you could fix that? but it's an optional request.

Done.
Also, "npm run build" work fine from web-components as well

2024-07-30 14:09 UTC, rohitsahu commented on libs/deps/mas/merch-card-all.js
> +\f\r]`,M=/<(?:(!--|\/[^a-zA-Z])|(\/?[a-zA-Z][^>\s]*)|(\/?$))/g,Le=/-->/g,Ue=/>/g,_=RegExp(`>|${se}(?:([^\\s"'>=/]+)(${se}*=${se}*(?:[^
@3ch023  not sure if I should try to manually fix this vulnerability. What's the workaround?

2024-07-30 14:35 UTC, 3ch023 commented
Hi @rohitsahu I tried to test it on the prod page where the bug was reported and it seems to still not work with your changes, could you please take a look?
https://main--cc--adobecom.hlx.live/products/photoshop/free-trial-download?milolibs=mwpw-152181-2--milo--rohitsahu

2024-07-30 16:49 UTC, 3ch023 approved these changes

2024-07-30 16:53 UTC, Axelcureno approved these changes

2024-07-31 14:12 UTC, 3ch023 approved these changes

2024-07-31 15:51 UTC, Axelcureno approved these changes

2024-08-01 08:45 UTC, Priyankavgit commented
I've validated the issue on the Milo pages using the fork branch, and the issue has been resolved. The pull requests have been updated with the 'Ready for Stage' label.
Jira Ticket: https://jira.corp.adobe.com/browse/MWPW-152181

2024-08-02 14:33 UTC, overmyheadandbody reviewed
I'm not sure I'm getting this. On https://mwpw-152181-2--milo--rohitsahu.hlx.page/drafts/rosahu/rosahu, pressing Tab after the last element of a merch card doesn't do anything. For example, in this screenshot, the focused element is the "Buy Now" one from the first card. Pressing Tab has no effect, the focus remains on that element. Pressing Shift + Tab focuses the previous link, which is correct. My expectation would be that pressing Tab in this scenario would focus the link from "This is the green promo text with link" from the next card.
<img width="927" alt="Screenshot 2024-08-02 at 16 29 45" src="https://github.com/user-attachments/assets/9bbc5885-df57-4f69-9a1a-4a9f3d188556">

I'm not requesting changes, since that's the current behavior on production as well, but to me it looks like there's still an issue to be solved. Am I testing in the right place? Is this another bug that needs to be treated separately?

2024-08-05 09:14 UTC, merged