MWPW-153629: [Mini compare] Stack cards on mobile
adobecom/milo pull request #2675
Opened 2024-07-31 18:13 UTC by Axelcureno

Removes mobile styles for mini compare chart and instead stacks them all in one column.

Resolves: https://jira.corp.adobe.com/browse/MWPW-153629

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card
- After: https://mwpw-153629--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card

2024-07-31 23:59 UTC, Roycethan requested changes
@Axelcureno 
1)Some rows are having more empty spaces and not adjusted accordingly
https://main--cc--adobecom.hlx.live/creativecloud?milolibs=mwpw-153629--milo--adobecom
<img width="930" alt="image" src="https://github.com/user-attachments/assets/dd3f4224-82ff-4a15-9b49-3d81adb6753e">
2) More empty spce before the CTA's
https://main--cc--adobecom.hlx.live/cz/creativecloud?milolibs=mwpw-153629--milo--adobecom
3)For Tablet : it should be two column layput per latest XD even in Individuals tab:
Need to adjust:
https://main--cc--adobecom.hlx.live/cz/creativecloud?milolibs=mwpw-153629--milo--adobecom
<img width="930" alt="image" src="https://github.com/user-attachments/assets/2a43bcfa-a56d-4e83-a3b9-b2db231ea01e">

<img width="930" alt="image" src="https://github.com/user-attachments/assets/f323055c-bd0b-4180-93f3-2850e2ef8867">

2024-08-01 00:05 UTC, Axelcureno commented
@Roycethan I'm seeing different, can you try refreshing the page when switching to mobile / tablet? This extra space is added normally when window is resized and not refreshed, since we calculate height with js.

![Screenshot 2024-07-31 at 5 03 32 PM](https://github.com/user-attachments/assets/1466a9c0-d365-43ac-b4e7-d03128d69cb5)
![Screenshot 2024-07-31 at 5 02 48 PM](https://github.com/user-attachments/assets/ac293ee4-1073-4736-863b-2b241c3b0227)

2024-08-01 00:25 UTC, Roycethan requested changes
All the above 3 issues are different and are reproducible even at page refresh.  #1  although happens when scrolling down - scroll down adding extra padding or disturbing the calculation.
#2 and #3 are reproducible
Let me know if more details to reproduce needed

2024-08-01 23:02 UTC, Roycethan commented on libs/deps/mas/merch-card-all.js
> +\f\r]`,M=/<(?:(!--|\/[^a-zA-Z])|(\/?[a-zA-Z][^>\s]*)|(\/?$))/g,Pe=/-->/g,Ne=/>/g,_=RegExp(`>|${ie}(?:([^\\s"'>=/]+)(${ie}*=${ie}*(?:[^
@Axelcureno Can you plz review/fix these ? thanks

2024-08-01 23:04 UTC, Roycethan approved these changes
Marked issues are resolved, approving, Needs to be verified post other reviews for regressions

2024-08-06 09:55 UTC, bozojovicic approved these changes

2024-08-06 11:19 UTC, yesil commented on libs/features/mas/web-components/src/merch-card.js
> +    get isMobile() {
can we move this in utils.js?

2024-08-06 20:36 UTC, Axelcureno commented on libs/features/mas/web-components/src/merch-card.js
> +    get isMobile() {
Done

2024-08-13 12:46 UTC, mirafedas commented on libs/deps/mas/merch-card-all.js
> +\f\r]`,P=/<(?:(!--|\/[^a-zA-Z])|(\/?[a-zA-Z][^>\s]*)|(\/?$))/g,Le=/-->/g,Ue=/>/g,_=RegExp(`>|${se}(?:([^\\s"'>=/]+)(${se}*=${se}*(?:[^
@Axelcureno I added `libs/deps/mas` to `.github/codeql/codeql-config.yml`, but my PRs are not merged yet, you can add it as well to make this check pass

2024-08-13 13:18 UTC, 3ch023 approved these changes

2024-08-14 16:30 UTC, Roycethan requested changes
@Axelcureno Price Font sizes are of 24 px at https://main--cc--adobecom.hlx.live/creativecloud?milolibs=mwpw-153629--milo--adobecom
they are at about 16 px at Main, plz check thanks

2024-08-14 18:18 UTC, Roycethan commented
> @Axelcureno Price Font sizes are of 24 px at https://main--cc--adobecom.hlx.live/creativecloud?milolibs=mwpw-153629--milo--adobecom they are at about 16 px at Main, plz check thanks

Fixed

2024-08-14 18:25 UTC, Roycethan requested changes
@Axelcureno 
AC: Suppress the empty rows

Still see Empty rows exists:
<img width="800" alt="image" src="https://github.com/user-attachments/assets/717080bd-1a15-4e78-aec2-fb1635224abb">

2024-08-14 21:19 UTC, Axelcureno commented
> @Axelcureno AC: Suppress the empty rows
> 
> Still see Empty rows exists: <img alt="image" width="800" src="https://private-user-images.githubusercontent.com/104928176/357953529-717080bd-1a15-4e78-aec2-fb1635224abb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NzA1ODUsIm5iZiI6MTcyMzY3MDI4NSwicGF0aCI6Ii8xMDQ5MjgxNzYvMzU3OTUzNTI5LTcxNzA4MGJkLTFhMTUtNGU3OC1hZWMyLWZiMTYzNTIyNGFiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQyMTE4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmJjYzc5Yjg4M2U4MDJjZjA1NDRmNDg1NDc3NWRiZmVmZDNjMmU2NTNlYzc2NGEyYzE3YWU5OGE0MzY2YjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.THGnXoFQRf9_h1RjpRsNQoPktlKBP0a3-_kYbNPNb3I">

I have removed the empty rows @Roycethan

2024-08-14 22:50 UTC, Roycethan commented
> > @Axelcureno AC: Suppress the empty rows
> > Still see Empty rows exists: <img alt="image" width="800" src="https://private-user-images.githubusercontent.com/104928176/357953529-717080bd-1a15-4e78-aec2-fb1635224abb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NzA1ODUsIm5iZiI6MTcyMzY3MDI4NSwicGF0aCI6Ii8xMDQ5MjgxNzYvMzU3OTUzNTI5LTcxNzA4MGJkLTFhMTUtNGU3OC1hZWMyLWZiMTYzNTIyNGFiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQyMTE4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmJjYzc5Yjg4M2U4MDJjZjA1NDRmNDg1NDc3NWRiZmVmZDNjMmU2NTNlYzc2NGEyYzE3YWU5OGE0MzY2YjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.THGnXoFQRf9_h1RjpRsNQoPktlKBP0a3-_kYbNPNb3I">
> 
> I have removed the empty rows @Roycethan

Fixed Thanks

2024-08-19 08:12 UTC, merged