fix(MWPW-148801):Removed sticky header feature from all mobile devices.
adobecom/milo pull request #2744
Opened 2024-08-14 13:08 UTC by sharath-kannan

Re-opening this PR by making changes to the existing variant for the sticky-header.
Removed the sticky header variant from mobile devices as sticky header with a long text content would hide all of the rows beneath it.

* Added min-width for table Cta button.
* Removed sticky header for mobile devices.

Resolves: [MWPW-148801](https://jira.corp.adobe.com/browse/MWPW-148801)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/sharathkannan/plans?martech=off
- After: https://mwpw-148801--milo--sharath-kannan.hlx.page/drafts/sharathkannan/plans?martech=off

2024-08-21 12:39 UTC, overmyheadandbody commented on libs/blocks/table/table.css
> +    max-width: 70%;
PR description states:
> Added min-width for table Cta button
which doesn't seem to match this declaration.

Furthermore, `70%` seemed a bit arbitrary to me, so I had a look at a few use-cases and I'm not sure this is the way to go. I limited the CTA's parent, `.action-area` to `max-width: 100%` and applied an `overflow: hidden` to the CTA. Here are a few use-cases comparing this approach (left column) to the one suggested in this PR (right column):

| 360px (70% still overflows) | 768px (70% spans multiple rows) | 1200px (70% spans multiple rows) |
| ------------- | ------------- | ------------- |
| ![Screenshot 2024-08-21 at 14 35 04](https://github.com/user-attachments/assets/fee9a34b-3f91-4d90-aa7f-aff0041cbdc8) | ![Screenshot 2024-08-21 at 14 36 30](https://github.com/user-attachments/assets/4c10306b-70e0-4605-a2a3-904ec87246d7) | ![Screenshot 2024-08-21 at 14 37 41](https://github.com/user-attachments/assets/ad5b06fb-b498-4ddd-ab40-b743800b8bd1) |

2024-08-21 15:11 UTC, overmyheadandbody requested changes
Blocking this since it triggered some controversy on the authoring side as to whether this is the default behavior we want.

2024-09-02 16:07 UTC, overmyheadandbody approved these changes
Make sure to rebase your changes to the latest `stage` branch, as some updates have been pushed for the `table` block. That would be helpful for QA purposes.

It would also be helpful to add some more examples to the test page with variations of all 3 possibilities.

2024-09-04 09:36 UTC, drashti1712 approved these changes

2024-09-05 09:26 UTC, overmyheadandbody commented
Hey @sharath-kannan! I see this has the required approvals, is there a QE that can look into getting this tested?

2024-09-05 10:15 UTC, Anupamasonnalagi commented
Verified the PR. Button in the table is proper in iPhone device and content is visible.
Completed the regression. Details are there in JIRA: [MWPW-157739](https://jira.corp.adobe.com/browse/MWPW-157739)

2024-09-05 16:45 UTC, merged