[MWPW-158021] Move Nala tests to Milo Repo
adobecom/milo pull request #2847
Opened 2024-09-08 19:09 UTC by skumar09

Move following Nala tests to Milo Repo

- accordion
- aside
- action-item
- carousel

Resolves: [MWPW-158021](https://jira.corp.adobe.com/browse/MWPW-158021)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/?martech=off
- After: https://nala--milo--skumar09.hlx.page/?martech=off

2024-09-09 09:10 UTC, mokimo approved these changes
Great! Lovely to see more nala tests moving in

2024-09-09 13:14 UTC, jk commented on nala/features/osttools/ost.spec.js
> +      tags: '@ost @commerce @regression @nopr @jk',
@afmicka make sure to escape GitHub handles in your comments to prevent unintended notifications

2024-09-09 14:18 UTC, afmicka commented
@skumar09 OST tests are not being executed under commerce nor ost tag. It does not find the tests at all. Do you know why? The other commerce tests are executing  OK with the tags.

`npm run nala stage @ost`

<img width="512" alt="Screenshot 2024-09-09 at 16 07 31" src="https://github.com/user-attachments/assets/ed842a20-7854-4f03-939e-61ec7a34ba6d">

2024-09-09 14:33 UTC, afmicka approved these changes

2024-09-09 16:35 UTC, JackySun9 approved these changes

2024-09-09 17:57 UTC, Dli3 approved these changes

2024-09-10 17:16 UTC, JackySun9 commented
@skumar09 please fix this

2024-09-11 12:22 UTC, robert-bogos approved these changes

2024-09-11 18:33 UTC, TsayAdobe requested changes
Please add the nala directory to`.hlxignore`

2024-09-12 06:01 UTC, TsayAdobe approved these changes

2024-09-16 08:54 UTC, merged