MWPW-159113 [Personalization] Parallelize personalization network requests to be as efficient as possible
adobecom/milo pull request #2970
Opened 2024-09-27 06:57 UTC by sharmrj

* Network requests, entitlements.js, promo-utils.js (if needed), and the manifest files are now made concurrently.

This optimization won't immediately bear fruit since it reveals a different bottleneck
Before: 
![image](https://github.com/user-attachments/assets/ae83493f-5a2a-4927-993f-344509ec2765)

After:
![image](https://github.com/user-attachments/assets/066f47ca-7f24-4055-9582-87d5be9002f8)

Once entitlements.js, promo-utils.js, and the manifests load concurrently, we find that launch becomes our bottleneck, so thi optimization needs to be combined with two subsequent optimizations in order to bear fruit. Note that photoshop.json takes less time to load in prod environments, so launch is more likely to be bottleneck in prod.

1. Launch.js needs to be split up/optimized. Related tickets: https://jira.corp.adobe.com/browse/MWPW-158739, https://jira.corp.adobe.com/browse/MWPW-158749
2. The request for the manifest files may need to be made earlier (this depends on how long it takes to load in prod with the prior optimizations, since manifest files take less time to laod on prod.). We'll have to wait for prior optimizations to be done to decide the next step.

Resolves: [MWPW-159113](https://jira.corp.adobe.com/browse/MWPW-159113)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/?martech=off
- After: https://par-pers--milo--sharmrj.hlx.page/?martech=off

https://main--cc--adobecom.hlx.page/products/photoshop?milolibs=par-pers--milo--sharmrj
Note: due to franklin code cache issues, some parts of the page, like the gnav, don't load correctly. But the above page is sufficient to see that the calls are being correctly parallelized.

2024-09-27 09:23 UTC, mokimo reviewed
Very cool to see this being tackled, with MEP/Personalization we should have room for improvements in terms of performance.

2024-09-27 09:23 UTC, mokimo commented on libs/features/personalization/personalization.js
> +  manifests = await Promise.all((await Promise.all(manifestPromises))
Is the double `Promise.all` there for any specific reason, or is that an omission?

```js
// Untested demo code
manifests = await Promise.all(
  manifestPromises.map(async (promise) => {
    try {
      const resp = await promise;
      if (!resp.ok) {
        if (resp.status === 404) {
          throw new Error('File not found');
        }
        throw new Error(`Invalid response: ${resp.status} ${resp.statusText}`);
      }
      const manifestData = await resp.json();
      return { manifestData, manifestPath: resp.url };
    } catch (e) {
      console.log(`Error loading content: ${resp.url}`, e.message || e);
      return null;
    }
  })
).then(results => results.filter(Boolean));
```

2024-09-27 11:11 UTC, sharmrj commented
@mokimo pointed out an issue where we're waiting a long time in between the interact call and loading the blocks.

Turns out, if launch finishes loading before the ims token network request completes, the page stalls for 4 extra seconds while we wait for the alloy event (even though the interact call goes through just fine). I've confirmed this by making measurements of `getTargetPersonalization` like so:
```javascript
 performance.mark('targetstart');
    const { targetManifests, targetPropositions } = await getTargetPersonalization();
    performance.mark('targetend');
    console.log(performance.measure('target', 'targetstart', 'targetend'));
```
If launch loads before the ims token comes back we always get a 4second timing on this function: 
```
PerformanceMeasure {detail: null, name: 'target', entryType: 'measure', startTime: 5821.900000095367, duration: 4000.899999976158}
```
Note that the timeout duration in martech.js is exactly 4000ms.
If the ims token comes back before launch we get something more along the lines of:
```
PerformanceMeasure {detail: null, name: 'target', entryType: 'measure', startTime: 8346.5, duration: 596.2999999523163}
```
This is possibly why some Nala tests are timing out.

AFAICT this sometimes happens out in the wild, it's just that this optimization makes it more likely to happen. I'll continue to investigate the root cause.

2024-10-08 17:11 UTC, vgoodric requested changes
Please let me know when this is finalized so we can thoroughly QA it.  SOT approval often does not check for MEP.

2024-10-17 12:00 UTC, 3ch023 commented on libs/features/personalization/personalization.js
> +    const { default: getPromoManifests } = await promoUtilsPromise;
we could also move code from promo-utils.js directly here, i think it was not a good decision in the first place to have a separate file.
promo-utils.js contents seem small enough

2024-10-17 12:07 UTC, 3ch023 commented on libs/features/personalization/personalization.js
> +    .filter((m) => !('disabled' in m) || !m.disabled)
if i remember correct, we shouldn't filter out disabled manifests.
those are 'promotions' manifests that are schedule is in the future/past, but Content Authors need to see them in the Page mep preview interface. However we don't load the .json itself (at least this is how it used to work) unless the manifest is active.

if you are still able to see a disabled manifest in the page then we are good

2024-11-07 07:58 UTC, sharmrj commented
For whatever reason I'm seeing the timeout issue again after merging the stage branch into my branch and fixing the merge conflicts. It seems IMS loaded after launch and that's what triggered the issue again:
![image](https://github.com/user-attachments/assets/5f9e3dbd-0485-41ed-9930-c363f2b420b5)
![image](https://github.com/user-attachments/assets/43fb8a99-89e7-4929-82a2-784c25387b4e)
I'll attach the trace here: 
[Trace-20241107T131821.json.zip](https://github.com/user-attachments/files/17657964/Trace-20241107T131821.json.zip)

2024-11-08 13:28 UTC, chrischrischris commented on libs/features/personalization/personalization.js
> +      return fetch(normalizedURL, { mode: 'same-origin' });
nit: inline `normalizePath`

2024-11-08 13:28 UTC, chrischrischris commented on libs/features/personalization/personalization.js
> +      if (pzn) loadLink(getXLGListURL(config), { as: 'fetch', crossorigin: 'anonymous', rel: 'preload' });
Doesn't this line still need to run even when the manifest loading is successful?

2024-11-22 07:31 UTC, sharmrj commented
> For whatever reason I'm seeing the timeout issue again after merging the stage branch into my branch and fixing the merge conflicts. I was also unable to reproduce the issue earlier which is why I thought it had been resolved. It seems IMS loaded after launch and that's what triggered the issue again: ![image](https://private-user-images.githubusercontent.com/118168183/383865857-38ba62b4-ecad-4c83-ab2f-2bb0f8bdcd0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNTkxMzYsIm5iZiI6MTczMjI1ODgzNiwicGF0aCI6Ii8xMTgxNjgxODMvMzgzODY1ODU3LTM4YmE2MmI0LWVjYWQtNGM4My1hYjJmLTJiYjBmOGJkY2QwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQwNzAwMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmVhYjczZjYxZDE5Nzk4NTRhZTMxZTRhZDNiMjE3MWY0N2I0OGRiYWJlZjFiY2U4YzFjMTQ4NzRhODg1ZWRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ITDsKZm0_xTHq0xSsJ_T_cf3XBQ6cHWDOgRnYiwDre4) ![image](https://private-user-images.githubusercontent.com/118168183/383865943-0e169ca2-4e94-4c18-abca-1253ea413092.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNTkxMzYsIm5iZiI6MTczMjI1ODgzNiwicGF0aCI6Ii8xMTgxNjgxODMvMzgzODY1OTQzLTBlMTY5Y2EyLTRlOTQtNGMxOC1hYmNhLTEyNTNlYTQxMzA5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQwNzAwMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjlhMWEwNmI3ZDRhZDU0ZmI3NzZiMTVmNmNmZjU3OWFiNmE4NGY4MDc1YjNjNDQ0OGViZTUyZWFlM2RhMTExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uLyohjBwpZLztIBS1IoOfrSe7k6gqGum3-aE5DuM12Q)
> 
> I'll attach the trace here: [Trace-20241107T131821.json.zip](https://github.com/user-attachments/files/17657964/Trace-20241107T131821.json.zip)

Turns out the same issue exists in helpx as well. In this case the timeout is 3 seconds instead of four, and it causes the global nav to load late.

![Screenshot 2024-11-22 at 12 58 17 PM](https://github.com/user-attachments/assets/236a3865-ad67-4cb3-a7ec-67eb45018f32)


It's easier to see in the trace:  [Trace-20241122T125841.json.zip](https://github.com/user-attachments/files/17866514/Trace-20241122T125841.json.zip)

The relevant gap is from `feds.js` to `helpx.adobe.com.html`

It's possible that the cause is that main.min.js loads before ims (rather than launch).

2024-12-07 01:40 UTC, closed without merging