MWPW-159356: Merch Card grid misalignment fix
adobecom/milo pull request #2984
Opened 2024-09-30 17:41 UTC by Axelcureno

Fixes merch card grid misalignment caused when MEP manipulates the DOM by forcing cards to stretch normally.

Resolves: [MWPW-159356](https://jira.corp.adobe.com/browse/MWPW-159356)

**Impacted URL**
https://main--cc--adobecom.hlx.page/products/special-offers?instant=2024-11-15T14:00:00.000Z&milolibs=MWPW-159356--milo--adobecom&martech=off

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card&martech=off
- After: https://MWPW-159356--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card&martech=off

2024-10-03 12:20 UTC, mirafedas approved these changes

2024-10-03 15:24 UTC, Roycethan requested changes
@Axelcureno On safari the prices and CTA's arae not resolved for offers. Looks like the branch has same issue which we saw earlier...
ex: https://main--cc--adobecom.hlx.page/products/special-offers?instant=2024-11-15T14:00:00.000Z&milolibs=MWPW-159356--milo--adobecom&martech=off
<img width="1497" alt="image" src="https://github.com/user-attachments/assets/7e15c0e8-4caa-4a86-b348-3b1a2ffba662">
cc @npeltier

2024-10-04 01:02 UTC, Roycethan approved these changes

2024-10-04 01:03 UTC, Roycethan commented
@Axelcureno Verified , Need one more approval for review cc @npeltier

2024-10-08 07:44 UTC, yesil approved these changes

2024-10-21 09:23 UTC, merged