MWPW-159032: Defaults to empty alt tag on the svg - Accessibility requirement
adobecom/milo pull request #3016
Opened 2024-10-04 16:43 UTC by joaquinrivero

This exist before, and we are getting request by accessibility to added again for unity project

Defaults to empty alt tag on the image if no alt text is authored. Per accessibility best practices this declares the image as "decorative".

Resolves: [MWPW-159032](https://jira.corp.adobe.com/browse/MWPW-159032)

**Test URLs:**

- Before: https://main--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf-projectunity?martech=off
- After: https://main--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf-projectunity?martech=off&milolibs=MWPW-159032-svg--milo--joaquinrivero

2024-10-04 22:03 UTC, meganthecoder approved these changes

2024-10-05 00:17 UTC, TsayAdobe approved these changes

2024-10-05 00:17 UTC, TsayAdobe commented on libs/utils/utils.js
> +    img.alt = altText || '';
How about adding it to the `creatTag` line.
```
const img = createTag('img', { loading: 'lazy', src, alt:  altText || ''});
```

2024-10-18 15:19 UTC, overmyheadandbody requested changes
Hi @joaquinrivero! Thanks for the contribution! This is quite important for accessibility. This comment's purpose is to:
1. Unmark this PR as stale :)
2. Ask that you please integrate @TsayAdobe's suggestion
3. Note that this is a great first step, but we'll likely need a few more changes to count this accessibility issue as solved. The codebase contains a bunch of inline SVGs that should get an `alt` tag as well. There are also other methods used to load SVGs, such as [this one](https://github.com/adobecom/milo/blob/stage/libs/blocks/share/share.js#L5). Additional stories will likely be created and taken through the regular Master Backlog intake process.

2024-10-28 11:17 UTC, overmyheadandbody approved these changes
If not done already, please rebase this with the `stage` branch, that should get some tests passing as well. It would also be helpful to add a test link that PSI can check to get the checks green. Thanks!

2024-10-31 17:33 UTC, tedAir reviewed
I don't see alt is defined for the fill and sign image in https://main--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf-projectunity?martech=off&milolibs=MWPW-159032-svg--milo--joaquinrivero.

2024-11-04 17:50 UTC, merged