Mwpw 157946
adobecom/milo pull request #3031
Opened 2024-10-09 20:23 UTC by sheridansunier

The sort options were not consistent in their use of ":" so we cleaned that up.

Before:
![image](https://github.com/user-attachments/assets/0f2f5ddd-6646-4ffc-b5b9-eb7acb8227b8)

After:
![image](https://github.com/user-attachments/assets/eedfbaba-a854-404c-b044-45c2d8167298)

Resolves: [MWPW-157946](https://jira.corp.adobe.com/browse/MWPW-157946)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/?martech=off
- After: https://MWPW-157946--milo--sheridansunier.hlx.page/?martech=off

2024-10-15 18:27 UTC, cmiqueo approved these changes

2024-10-15 19:24 UTC, gmirijan approved these changes

2024-10-16 17:40 UTC, gmirijan requested changes
@sheridansunier Please update sort list option of the Modified Date as 
Modified Date: (Newest to Oldest)
Modified Date: (Oldest to Newest)

2024-10-16 21:07 UTC, gmirijan approved these changes

2024-10-23 15:24 UTC, merged