MWPW-159555 Add support for lana-sample query param
adobecom/milo pull request #3045
Opened 2024-10-15 19:37 UTC by chrischrischris

The `lana-sample` query param will override any sample rate defined elsewhere.  Setting it to "100" will force lana to send everything to splunk.

Resolves: [MWPW-159555](https://jira.corp.adobe.com/browse/MWPW-159555)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/?martech=off
- After: https://mwpw-159555--milo--adobecom.hlx.page/?martech=off

2024-10-15 20:18 UTC, sukamat approved these changes

2024-10-15 20:45 UTC, rgclayton approved these changes

2024-10-16 07:58 UTC, SilviuLCF commented
Hi @chrischrischris can you provide some guidance on how testing should be performed for this change? 

thank you

2024-10-16 08:19 UTC, overmyheadandbody approved these changes

2024-10-16 08:19 UTC, overmyheadandbody commented on libs/utils/lana.js
> +/* eslint-disable */
Is this needed for the whole file? I'd rather have ESLint disabled for specific purposes, otherwise we might miss a lot of errors.

2024-10-16 11:38 UTC, overmyheadandbody commented
Seems the new unit test is failing - `❌ LANA > The lana-sample query param overrides existing sampleRate`

2024-10-17 09:56 UTC, mokimo approved these changes

2024-10-17 22:03 UTC, thedoc31 requested changes
Assuming someone will always send in a valid integer between 0 and 100 is dangerous without any (apparent) input validation or error handling. What happens if I send in an invalid number or a value long enough to be a BigInt? Would lana know what to do if it got a NaN in this param?

2024-10-18 18:11 UTC, chrischrischris commented
@thedoc31 The `parseInt` handles the sanitization of the input.  If the `lana-sample` param is invalid it will be `NaN` and the next line will ignore it:

```
const sampleRateParam = parseInt(new URL(window.location).searchParams.get('lana-sample'), 10);
const sampleRate = sampleRateParam || (o.errorType === 'i' ? o.implicitSampleRate : o.sampleRate);
```

It's fine if the param is negative or a gigantic number.  Negative will behave like 0, anything over 100 behaves like 100.

2024-10-21 07:45 UTC, SilviuLCF approved these changes
Verified, ready to STAGE

2024-10-28 09:18 UTC, merged