[MWPW-148000] [ANALYTICS] Add analytics to Modals
adobecom/milo pull request #3130
Opened 2024-11-01 21:40 UTC by AdobeLinhart

Analytics are automatically added to main, but are modals outside of main? Modals should have analytics automatically added as well.

Notes:

The function for adding analytics is called `decorateSectionAnalytics` in libs/martech/attributes.js
that function is called in libs/utils/utils.js
Could/should we include the name of the modal?

Instructions on creating a modal: https://milo.adobe.com/docs/authoring/create-modal

Resolves: [MWPW-148000](https://jira.corp.adobe.com/browse/MWPW-148000)

https://main--cc--adobecom.hlx.page/drafts/mepdev/fragments/2024/q4/modalanalytics/marquee?milolibs=local#testmodal
**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/?martech=off
- After: https://<branch>--milo--adobecom.hlx.page/?martech=off

2024-11-01 23:58 UTC, markpadbe commented on libs/martech/attributes.js
> +  const id = Number.isNaN(idx) ? `s${idx + 1}` : idx;
```suggestion
  const id = !Number.isNaN(idx) ? `s${idx + 1}` : idx;
```

2024-11-04 18:17 UTC, AdobeLinhart commented on libs/martech/attributes.js
> +  const id = Number.isNaN(idx) ? `s${idx + 1}` : idx;
Updated.

2024-11-04 19:58 UTC, markpadbe requested changes

2024-11-04 19:58 UTC, markpadbe commented on libs/martech/attributes.js
> +  const id = Number.isNaN(idx) ? `s${idx + 1}` : idx;
sorry, I think I'm seeing issues with !Number.isNaN in the modal tests. maybe try this:
```suggestion
  const id = Number.isInteger(idx) ? `s${idx + 1}` : idx;
```

2024-11-04 21:55 UTC, qiyundai approved these changes
LGTM

2024-11-04 21:56 UTC, markpadbe approved these changes

2024-11-05 17:58 UTC, vgoodric commented on libs/blocks/modal/modal.js
>    dialog.append(close);
```suggestion
  decorateSectionAnalytics(dialog, `${id}-modal`, getConfig());
  dialog.append(close);
```

2024-11-06 09:17 UTC, merged