Fix(mwpw:160737): Favicon fix for safar pinned tab
adobecom/milo pull request #3172
Opened 2024-11-11 10:18 UTC by sharath-kannan

* safari fav icons will display favicon-180.png as fallback for safari version 16.

Resolves: [MWPW-160737](https://jira.corp.adobe.com/browse/MWPW-160737)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/?martech=off
- After: https://favicon--milosh--sharath-kannan.hlx.live/?martech=off
cc test url
 https://mwpw-160737--cc--sharath-kannan.hlx.live/creativecloud?milolibs=favicon--milosh--sharath-kannan

2024-11-11 10:41 UTC, sharmrj approved these changes

2024-11-11 10:41 UTC, bandana147 approved these changes

2024-11-11 10:42 UTC, drashti1712 approved these changes

2024-11-11 18:55 UTC, skumar09 requested changes
Please check and fix the nala marchCard tests

2024-11-12 07:33 UTC, spadmasa commented
Valdiation done in pr in safari browser in Mac safari version 16.6 and iphone safari, able to see favicon and new logo coming up when clicked on add to home screen
![{F120CCAE-C01E-4FC9-85FA-2F1BBC645393}](https://github.com/user-attachments/assets/f8f9cc65-9385-47d5-a5fe-1c54051f378e)

2024-11-12 08:21 UTC, closed without merging

2024-11-12 08:22 UTC, sharath-kannan commented
closed PR since this is not needed.