MWPW-156157 use OST v1.19.1
adobecom/milo pull request #3290
Opened 2024-12-02 15:10 UTC by npeltier

will use www.adobe.com cached calls of WCS, check for https://MWPW-156157--milo--adobecom.aem.page/tools/ost?token=<...>

**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/?martech=off
- After: https://MWPW-156157--milo--adobecom.aem.page/?martech=off

2024-12-02 15:14 UTC, yesil approved these changes

2024-12-02 16:30 UTC, 3ch023 approved these changes

2024-12-02 16:34 UTC, 3ch023 requested changes
tried on https://mwpw-156157--milo--npeltier.hlx.page/tools/ost?token=<token>, seeing this 
![image](https://github.com/user-attachments/assets/1d905981-4ca6-43ed-963a-7ec7505c1a9a)

2024-12-03 13:24 UTC, npeltier commented
@3ch023 flushed my code cache, please have a look again

2024-12-03 17:31 UTC, 3ch023 approved these changes

2024-12-03 18:17 UTC, Axelcureno approved these changes

2024-12-09 12:09 UTC, merged