Play and objectives icon addition
adobecom/milo pull request #335
Opened 2022-11-30 15:52 UTC by fullcolorcoder

Resolves: [MWPW-121791](https://jira.corp.adobe.com/browse/MWPW-121791)

**Test URLs:**
[Before](https://main--milo--adobecom.hlx.page/drafts/bradjohn/document1?martech=off)
[After](https://customer-story-icons--milo--adobecom.hlx.page/drafts/bradjohn/document1?martech=off)

Bacom:
https://bradjohn-customer-story-svg--bacom--adobecom.hlx.page/drafts/bradjohn/document?milolibs=customer-story-icons&martech=off

2022-11-30 17:52 UTC, auniverseaway commented on libs/img/icons/icons.svg
> +  <symbol id="icon-results" viewBox="0 0 18 18">
I think the word icon is redundant.

2022-11-30 17:53 UTC, auniverseaway requested changes
Small change. :-)

2022-11-30 17:55 UTC, ryanmparrish commented on libs/img/icons/icons.svg
> +  <symbol id="icon-objectives" viewBox="0 0 18 18">
Same w/ this one. `icon-` can be omitted. from the id.

2022-11-30 21:08 UTC, ryanmparrish approved these changes

2022-12-07 19:38 UTC, chrischrischris approved these changes

2022-12-08 18:22 UTC, ryanmparrish commented
Seem like this is GTG. Verified!

2022-12-09 17:56 UTC, merged