Setting aria-live to shadowRoot element instead to the slot.
adobecom/milo pull request #3389
Opened 2024-12-17 21:55 UTC by seanchoi-dev

This is a followup PR from https://github.com/adobecom/milo/pull/3201

Resolves:
- [MWPW-162024](https://jira.corp.adobe.com/browse/MWPW-162024)

**Test URLs:**
- Before: https://main--milo--adobecom.aem.page/?martech=off
- After: https://MWPW-162024--milo--adobecom.aem.page/?martech=off

**Test for consumer site:**
- Before: https://main--cc--adobecom.hlx.page/products/catalog
- After: https://main--cc--adobecom.hlx.page/products/catalog?milolibs=MWPW-162024#category=creativity-design

2024-12-19 15:07 UTC, vhargrave approved these changes
I wonder if you could not add the aria-live attribute while directly adding that text field to your component, but doesn't matter too much
looks good!

2024-12-19 15:40 UTC, yesil requested changes

2024-12-19 15:40 UTC, yesil commented on libs/blocks/merch-card-collection/merch-card-collection.js
> +  merchCardCollection.shadowRoot.getElementById('resultText')?.setAttribute('aria-live', 'polite');
@vhargrave is right, we should not update `shadowRoot` from outside.
we should add it at libs/features/mas/src/merch-card-collection.js

2025-01-08 19:34 UTC, Roycethan approved these changes

2025-01-13 20:37 UTC, Axelcureno approved these changes

2025-01-14 09:15 UTC, merged