add images block
adobecom/milo pull request #339
Opened 2022-12-05 21:23 UTC by saugatmalla

* Migrate Images block
* Refactored
* Added test

Resolves: Images block migration

**Test URLs:**
- Before: [https://main--blog--adobecom.hlx.page/drafts/smalla/images](https://main--blog--adobecom.hlx.page/drafts/smalla/images)
- After: [https://main--blog--adobecom.hlx.page/drafts/smalla/images?milolibs=images](https://main--blog--adobecom.hlx.page/drafts/smalla/images?milolibs=images)

2022-12-06 17:22 UTC, vhargrave approved these changes

2022-12-06 17:22 UTC, vhargrave commented on libs/blocks/images/images.js
> +* Initializes the image block by wrapping each picture element in a div with a class of "figure"
nit: in my opinion we don't need this comment :)

2022-12-06 17:22 UTC, vhargrave commented on libs/blocks/images/images.js
> +export default function init(blockEl) {
can you run npm run lint on this file and fix the linting errors? 
On line 11 you're missing a semicolon after your return statement for example.

2022-12-07 19:28 UTC, chrischrischris approved these changes

2022-12-07 23:08 UTC, auniverseaway requested changes
We're missing the whole figure creation piece...

https://github.com/adobe/blog/blob/main/blocks/images/images.js#L18

2022-12-07 23:20 UTC, auniverseaway commented
Alright. I spoke with the big guns, we should change this block name to `figure`.

2022-12-08 22:04 UTC, saugatmalla commented
@auniverseaway I added `buildFigure` method and change the block name to `figure`.

@vhargrave @chrischrischris FYI

2022-12-12 21:36 UTC, auniverseaway approved these changes

2022-12-12 21:39 UTC, merged