MWPW-161354: MAS: export variant metadata
adobecom/milo pull request #3408
Opened 2024-12-24 12:55 UTC by yesil

to allow MAS Studio to toggle the fields
in the editor.

Resolves: [MWPW-161354](https://jira.corp.adobe.com/browse/MWPW-161354)

**Test URLs:**
- Before: https://main--milo--adobecom.aem.live/libs/features/mas/docs/mas.html
- After: https://mwpw-161354--milo--adobecom.aem.live/libs/features/mas/docs/mas.html

2025-01-08 13:53 UTC, 3ch023 commented on libs/features/mas/docs/styles.css
> +  display: flex;
imo we shouldn't have styles from merch-card in ccd.html (it's ok to have it on rest of pages)
reason is we have less change to catch an issue since ccd.html deviates from ccd usage by introducing additional styles. Example, in december, we had a space bug between prices that was only discovered on CCD build because in gallery it was 'fixed' by /docs/styles.css

I think on all gallery pages we shouldn't include <link rel="stylesheet" href="styles.css"> at all.

2025-01-08 13:56 UTC, 3ch023 requested changes
looks good, just a small comment

2025-01-08 15:16 UTC, yesil commented on libs/features/mas/docs/styles.css
> +  display: flex;
Good point @3ch023, let me remember why I have done this and find an alternative.

2025-01-17 11:32 UTC, 3ch023 approved these changes

2025-01-21 13:35 UTC, afmicka commented
@yesil commenting here but it may be related to mas PR instead of this. 
Checking https://mwpw-161354--mas--adobecom.hlx.live/studio.html?milolibs=mwpw-161354--milo--adobecom#path=drafts

The 'size' field for suggested card  - either it should be removed or it needs to have a default value instead of being empty. Earlier it had a text to enter the size but now is changed to drop down. Screenshots for comparison
<img width="1265" alt="Screenshot 2025-01-21 at 14 25 30" src="https://github.com/user-attachments/assets/633ad915-2e44-4a77-908a-a0582e2a50d3" />
<img width="295" alt="Screenshot 2025-01-21 at 14 27 07" src="https://github.com/user-attachments/assets/18f2cf77-691b-426f-83eb-119b2a2e832b" />

2025-01-22 14:55 UTC, afmicka commented
@yesil the id attribute is lost from the merch-card element. Do we want to lose it? Screenshots for comparison
<img width="659" alt="Screenshot 2025-01-22 at 15 53 02" src="https://github.com/user-attachments/assets/e78f05e7-2c05-4019-acbd-762d0050211c" />
<img width="947" alt="Screenshot 2025-01-22 at 15 53 09" src="https://github.com/user-attachments/assets/ae4b91a1-4118-423e-91f0-dbec4adca092" />

2025-01-22 15:05 UTC, afmicka commented
@yesil on your branch, one CTA disappears from the card. 
https://mwpw-161354--milo--adobecom.aem.live/docs/library/kitchen-sink/merch-card?martech=off
<img width="1317" alt="Screenshot 2025-01-22 at 16 02 36" src="https://github.com/user-attachments/assets/c312711f-df7e-4f1d-8203-25831fb80b9c" />
<img width="1337" alt="Screenshot 2025-01-22 at 16 02 46" src="https://github.com/user-attachments/assets/49eed0e5-ba14-4509-b472-628ca750cddd" />

2025-01-22 15:08 UTC, afmicka commented
@yesil disregard the previous message, was comparing .page with .live ... the change is not published,

2025-01-22 15:12 UTC, yesil commented
@afmicka yes, the following line was adding the ID it is dangerous as it could override the ID set by the consumer.


https://github.com/adobecom/milo/pull/3408/files#diff-c0e31e177931011ae39cb9321fdddb5cc8356f5df49a6ecf52e2b499c7564cdbL276

2025-01-27 08:33 UTC, merged