MWPW-120524 Append .html postfix for local links when hosting page ends with .html
adobecom/milo pull request #341
Opened 2022-12-07 17:37 UTC by chrischrischris

Resolves: [MWPW-120524](https://jira.corp.adobe.com/browse/MWPW-120524)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/?martech=off
- After: https://c3-htmlpostfix--milo--adobecom.hlx.page/?martech=off

2022-12-13 00:42 UTC, rgclayton reviewed
Are we still waiting for Franklin updates for this?

2022-12-14 16:52 UTC, auniverseaway commented
@rgclayton no.

2022-12-14 16:54 UTC, auniverseaway commented
This creates some issues with the home page (which you linked to). Can you look into it? I know those blocks are brittle since they're just the internal homepage blocks, but something seems amiss.

2022-12-14 16:54 UTC, auniverseaway requested changes
See above.

2022-12-20 18:01 UTC, auniverseaway commented on libs/utils/utils.js
> +    const blocks = el.querySelectorAll('div[class]:not(.content)');
```suggestion
    const blocks = section.querySelectorAll('div[class]:not(.content)');
```

2022-12-20 23:04 UTC, auniverseaway approved these changes

2023-01-03 20:37 UTC, rgclayton commented
Seeing a handful of console errors related to rum and lana when pointed to this feature branch that we don't see when pointing to main. Just wanted to verify the errors I'm seeing.

![image](https://user-images.githubusercontent.com/2539954/210437481-34394d8b-f2c5-4520-b405-769b0e70bfff.png)

2023-01-04 16:49 UTC, rgclayton approved these changes
All console errors are gone after that last update. Thanks Chris!

2023-01-04 19:31 UTC, merged