MWPW-129009: Video Loop Enhancement
adobecom/milo pull request #617
Opened 2023-04-04 21:16 UTC by JasonHowellSlavin

* Adds the ability to add a `&_noloop` after the `#_autoplay` hash param to video urls to prevent looping 

Resolves: [MWPW-129009](https://jira.corp.adobe.com/browse/129009)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/slavin/digital-trends-report?martech=off
- After: https://video-loop-options--milo--adobecom.hlx.page/drafts/slavin/digital-trends-report?martech=off

2023-04-04 23:02 UTC, rgclayton requested changes
I think we can simplify this. 

- `#_autoplay` autoplays and loops infinitely - already a pattern in use
- `#_autoplay1` autoplays and only plays on time - simple update to our existing pattern.

*Noteworthy: all autoplay features need to have `muted` in order to be autoplayed by the browser.

2023-04-04 23:13 UTC, rgclayton commented
The Jira ticket linked to this is broken. So, I'm not sure of the requirements this was created from.

There is a [ticket added to the Milo backlog](https://jira.corp.adobe.com/browse/MWPW-129087) that I created last week.

After asking some questions in the dexter-authoring Slack channel it was mentioned that setting video's to loop a specified amount of times (loop four times then stop) isn't a pattern. So, I don't think we add that feature unless there has been a specific request related to that. I think there is more discovery related to that discussion going on.  

cc: @auniverseaway

2023-04-05 22:14 UTC, rgclayton approved these changes
Your test link (after) needs updated to reflect code updates. 
Description also needs updated to reflect changes for clarity. 

Otherwise looking good.

2023-04-05 22:49 UTC, saugatmalla approved these changes

2023-04-10 16:54 UTC, merged