Faas env
adobecom/milo pull request #656
Opened 2023-04-21 21:44 UTC by seanchoi-dev

Issue to resolve:
https://adobe-mwp.slack.com/archives/C02A3PQSD51/p1682104409585409?thread_ts=1682101521.751589&cid=C02A3PQSD51

2023-04-21 21:47 UTC, meganthecoder requested changes
Won't this send everything without a search param to dev, even production?

2023-04-24 09:48 UTC, seanchoi-dev commented
> 

@meganthecoder  Good catch.

2023-04-24 10:47 UTC, honstar approved these changes

2023-04-24 15:54 UTC, auniverseaway approved these changes

2023-04-24 17:04 UTC, meganthecoder approved these changes

2023-04-24 18:05 UTC, merged