(MWPW-130268): add link markup creation.
adobecom/milo pull request #677
Opened 2023-05-01 14:58 UTC by VKniaz

Link markup creation.

Resolves: [MWPW-130268](https://jira.corp.adobe.com/browse/MWPW-130268)

2023-05-02 08:18 UTC, honstar commented
@VKniaz : can you please add `before` and `after` test urls? Thx

2023-05-03 12:46 UTC, yesil requested changes

2023-05-03 12:46 UTC, yesil commented on test/blocks/ost/mocks/wcs-artifacts-mock.json
> +{
this file should be minimised to contain only the minimal set of data and real ids/codes should be replaced with dumb ones.
All non used properties should be removed.

2023-05-03 12:49 UTC, honstar requested changes

2023-05-03 15:33 UTC, honstar approved these changes

2023-05-04 08:31 UTC, honstar commented
Just noticed in your `after` test url that the placeholder replacement for a CTA `Buy now` button is still not properly replaced.

<img width="820" alt="Screenshot 2023-05-04 at 10 25 45" src="https://user-images.githubusercontent.com/1764977/236150695-85800653-dc6c-4fb0-9027-438dac4b7063.png">

2023-05-04 14:21 UTC, VKniaz commented
@honstar Document updated, now before on top.

2023-05-08 06:54 UTC, yesil commented
@VKniaz  the `CTA-` prefix is still there.
![image](https://user-images.githubusercontent.com/330057/236755129-7b567f70-c7fe-4212-b5f1-013ffa6b4236.png)

2023-05-08 10:53 UTC, honstar commented
> @VKniaz the `CTA-` prefix is still there. ![image](https://user-images.githubusercontent.com/330057/236755129-7b567f70-c7fe-4212-b5f1-013ffa6b4236.png)

@yesil : this is expected in the `BEFORE` section from @VKniaz's test document where an old CTA link is still in use. The `AFTER` section shows the correct `Buy now` CTA button.

2023-05-08 11:36 UTC, yesil commented
@honstar I was checking it at https://mwpw-130268--milo--adobecom.hlx.page/drafts/ilyas/merch

I updated the CTA text and it looks good.
Thanks @VKniaz

2023-05-08 11:36 UTC, yesil approved these changes

2023-05-09 06:52 UTC, yesil commented
@VKniaz is it too much ask to update the unit tests?
e.g: https://github.com/adobecom/milo/blob/main/test/blocks/merch/mocks/body.html

2023-05-10 09:23 UTC, npeltier approved these changes

2023-05-10 10:15 UTC, merged