Skip failing tests
adobecom/milo pull request #724
Opened 2023-05-16 14:13 UTC by mokimo

Those two tests consistently fail

2023-05-16 14:43 UTC, overmyheadandbody approved these changes

2023-05-16 14:54 UTC, narcis-radu approved these changes

2023-05-16 14:54 UTC, narcis-radu commented on web-test-runner.config.mjs
> +            logger.log(test);
👍

2023-05-16 15:35 UTC, honstar approved these changes

2023-05-16 23:36 UTC, auniverseaway requested changes
We want to fix the root problem and not introduce a custom reporter that we have to maintain.

2023-05-17 07:58 UTC, mokimo commented
@auniverseaway The root problem is a bug/oversight in the custom reporter, for which I've opened a PR.

https://github.com/modernweb-dev/web/pull/2278 - since we can't control when/if that is getting merged, there's a lot of value in having that customReporter in the meantime IMO.

2023-05-19 02:48 UTC, auniverseaway commented
@mokimo My concern was that we were introducing a _replacement_ reporter, not an _additional_ reporter.

We don't want to be on the hook for maintaining a custom reporter over a couple of incorrectly written tests. Re-looking at what you have, I think we're fine... assuming my comment above is accurate.

Thanks for looking into this and sending a PR. Really appreciate it.

2023-05-19 02:49 UTC, auniverseaway approved these changes

2023-05-19 02:50 UTC, merged