Append region (country) display name to document title
adobecom/milo pull request #876
Opened 2023-06-20 01:47 UTC by hparra

Resolves: [MWPW-132671](https://jira.corp.adobe.com/browse/MWPW-132671)

**Test URLs:**

- Before: https://main--dc--adobecom.hlx.live/ar/acrobat/online/word-to-pdf
- After: https://main--dc--adobecom.hlx.live/ar/acrobat/online/word-to-pdf?milolibs=seo-title-region--milo--hparra

2023-06-20 13:15 UTC, mokimo commented
There should be no PRs in draft: https://github.com/adobecom/milo/wiki/Submitting-PRs#drafts-prs

2023-06-20 18:31 UTC, hparra commented on libs/scripts/scripts.js
>    pe: { ietf: 'es-PE', tk: 'oln4yqj.css' },
Line 30 `la: { ietf: 'es-LA', tk: 'oln4yqj.css' },` is completely wrong. The `la` geo is for Latin America, while the `LA` subtag is for Laos. There may be other preexisting mistakes like this.

2023-06-20 18:56 UTC, hparra commented on libs/scripts/scripts.js
> -  la: { ietf: 'es-LA', tk: 'oln4yqj.css' },
This is completely wrong. The la geo is for Latin America, while the LA subtag is for Laos. There may be other preexisting mistakes like this.

2023-06-21 17:20 UTC, auniverseaway requested changes
Blocking for now. I see several issues. WIll address when Milo Academy is over.

2023-06-22 00:29 UTC, hparra commented on libs/scripts/scripts.js
> +export default config;
TODO: Delete

2023-06-22 00:48 UTC, hparra commented
@auniverseaway Added config feature gate and full test coverage. All checks pass except enforce PR labels. Prefer to land https://github.com/adobecom/milo/pull/880 first and then refactor this to use those changes.

2023-07-10 23:19 UTC, auniverseaway commented
1. The existing IETFs in Milo are wrong and should be updated to your tag properties. This should make this new "tag" property no longer needed. We will have to check the other consumers, but my guess would be they are more accurate since it's production content.
2. I would opt for a human readable property for the name instead of `rdn`. My first thought is that `name` seems to make the most sense since we need this for both language and region (aka locale). Another option would be to make it authorable in metadata.
3. We don't want milo opted into this in its config. This whole feature _as a default_ was previously shot down at a VP level several years ago. You have the right idea, though: config > metadata.xlsx > page metadata is usually how we like to handle overriding w/ granularity. I personally don't see any site implementing this site-wide, but I'm also not opposed to having it supported in config.
4. Given that the majority of content will **_not_** use this feature, it shouldn't take so much precedence in the call stack... At a high level: it shouldn't happen before LCP and the code shouldn't live in utils. I would gate this into a separate file similar to our other opt-in features (georouting, rich results, etc.). My general rule is, "is this needed to get us to LCP?" if the answer is no, it should fire after LCP. Things like decorating links run the risk of being interacted with so we leave those CPU cycles in front of LCP.

2023-07-11 17:28 UTC, hparra commented
> 1. The existing IETFs in Milo are wrong and should be updated to your tag properties. This should make this new "tag" property no longer needed. We will have to check the other consumers, but my guess would be they are more accurate since it's production content.
> 2. I would opt for a human readable property for the name instead of `rdn`. My first thought is that `name` seems to make the most sense since we need this for both language and region (aka locale). Another option would be to make it authorable in metadata.

See [Changes to IETF Values in Milo](https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=seoteam&title=Changes+to+IETF+Values+in+Milo). I'm not going to change the IETF values. There is a lot of pushback here even when the IETF value is wrong, e.g. https://github.com/adobecom/bacom/pull/123, https://github.com/adobecom/cc/pull/72, https://github.com/adobecom/dc/pull/270. Instead, I prefer to use the `locales` object I updated in https://github.com/adobecom/milo/pull/915. 

> 3. We don't want milo opted into this in its config. This whole feature _as a default_ was previously shot down at a VP level several years ago. You have the right idea, though: config > metadata.xlsx > page metadata is usually how we like to handle overriding w/ granularity. I personally don't see any site implementing this site-wide, but I'm also not opposed to having it supported in config.

Not sure this is relevant. Each cloud defines it's own config, so the fact that Milo opts-in only affects the actual Milo website, and not the libs' consumers. I will have to make the `locales` change for each cloud. That's why https://github.com/adobecom/milo/pull/880 was proposed.

> 4. Given that the majority of content will **_not_** use this feature, it shouldn't take so much precedence in the call stack... At a high level: it shouldn't happen before LCP and the code shouldn't live in utils. I would gate this into a separate file similar to our other opt-in features (georouting, rich results, etc.). My general rule is, "is this needed to get us to LCP?" if the answer is no, it should fire after LCP. Things like decorating links run the risk of being interacted with so we leave those CPU cycles in front of LCP.

OK. We're changing the `<title>`, so the concern here what that this will fire too late for googlebot to pick up change.

2023-07-24 22:12 UTC, hparra commented
Use-case solved with #955 ✌️

2023-07-24 22:12 UTC, closed without merging